### ISSUE TITLE
After long sleep, status does not reflect actual if integrated was forced

### ISSUE THREAD

**Issue by airdrummingfool** [codykrieger/gfxCardStatus#109]
Thanks for this awesome app! It's one of my favorite OSX utilities. Here's an issue I've been experiencing:
1. Put computer into forced integrated mode
2. Sleep computer for a long time (so it writes RAM to disk and powers down)
3. Wake computer up

At this point, gfxCardStatus shows that the card is back in "Dynamic Switching" mode, but it is actually still forced to the integrated chip (as evidenced by nothing happening when plugging in an external monitor). To fix this, I must choose "Discrete Only"; then the discrete graphics card (and the external monitor) kicks on and I can flip back to "Dynamic Switching".

Note that I do a good amount of battery/AC power switching when the computer is asleep; If that could be part of it, I can do more controlled testing.

I'm on OSX 10.8.3 (it also happened on 10.8.2), with a 15" 2012 MBP.

**Comment by codykrieger** [comment]
Duping this forward to #312 to track a broader set of cases where the displayed status doesn't match the actual status.
