### ISSUE TITLE
Getting odd behavior on new MBP with Intel Iris and discrete NVIDIA

### ISSUE THREAD

**Issue by RyderD** [codykrieger/gfxCardStatus#132]
I need to switch several times between Integrated Only And Discrete Only to get it to function, and the icon stays lit for up to 10 seconds. Is gfxCardStatus compatible with Mavericks and the new MBPs? I've donated before, but happy to donate again to help fund getting this issues solved. Love gfxCardStatus!

**Comment by codykrieger** [comment]
Tracking in #310; closing.
