### ISSUE TITLE
Graphics switching to Discrete after all dependencies close.

### ISSUE THREAD

**Issue by ThetaSigma312** [codykrieger/gfxCardStatus#133]
If you set gfxCardStatus to Integrated Only, it will set itself to Discrete after all dependencies are closed.
For example if you set gfxCardStatus to Intergrated, then open VLC, and then close it, it will give a notification and switch to Discrete, and stay there until you switch back or set it to Dynamic Switching, in which OS X switches automatically to Integrated.

I am unable to test this on any other computers at the moment, however I am on a Mid-2010 Macbook Pro 17" running the latest version of 10.9.

**Comment by garyabart** [comment]
I have a mid 2010 15" MacBook pro also with the bad graphic card that decided to quit after upgrading to Yosemite. $400+ fix at Apple, Your gfx software allows me to continue using my MB pro.  Is there a way to lock in to the "intergrated" setting only? I have determined my MB pro is only stable in that mode.  I guess there was a recall a couple of years ago on this graphic card but mine was working fine until the Yosemite upgrade. My son and I purchased this same laptop at the same time, His is still working with Mountain Lion. Im no expert on this graphic card switching, any info will help. Gary B

**Comment by codykrieger** [comment]
@garyabart On 2010 machines, there is no safe way to do that. Sorry :(

**Comment by garyabart** [comment]
Wow thanks for the quick get back.   I was afraid of that, bummer.  As long as it stays in intergrated it works fine.  Thank You. A donation will be on its way soon.

gary b
www.electronfx.com <http://www.electronfx.com/>

**Comment by ThetaSigma312** [comment]
I compiled my own version with the Integrated lock feature, however, as stated by codykrieger, there is no perfect solution, but I've had no problems with it. I'll include a link to it in my dropbox. At each startup be sure to select Integrated Only, and it should stick to it, except for a split second when all dependancies are closed, hopefully it'll be fast enough where the failing GPU will cause problems.
https://www.dropbox.com/sh/oksstyg8xlx12fy/AACQjSLjGAfIGpfPL5UTjrWoa?dl=0
Hope it helps!

**Comment by garyabart** [comment]
Got it, Thank you thank you, Ill test and keep you posted.  This stuff is all out there for me.

gary b

**Comment by garyabart** [comment]
Thank you for the "gfxCardStatus.app" I have down loaded it but, excuse my dumbness what do I install from the contents folder?  It says gfx can't be opened because it is from a unidentified developer.

**Comment by ThetaSigma312** [comment]
Ah, I guess I never signed it. Go into System Preferences, then Security & Privacy, then on the line Allow apps downloaded from: change it to Anywhere.

That'll fix your problem, however it means that unsigned apps can be opened. But you will get a dialogue asking if you're sure you want to open an unsigned app, so it's still somewhat secure.

Use your best judgement. Personally I leave it on Anywhere.

**Comment by codykrieger** [comment]
Please *do not* allow unsigned apps. That's terrible. Instead, ctrl-click the app and hit Open. That'll give you another button in the dialog that comes up which will let you open it.

**Comment by ThetaSigma312** [comment]
Yikes, I totally forgot you could do that, thanks for reminding me.

**Comment by garyabart** [comment]
Didn’t go that far, it told me that gfx was not opened, do u want to open, I said yes,  it opened terminal, I don’t know terminal other than don’t  mess with it unless u know what your doing.

**Comment by ThetaSigma312** [comment]
Terminal? Did you only download the Contents file?

**Comment by garyabart** [comment]
opening the zip file created a contents folder, in there was a MacOS folder, that had gfxCardstatus, I opened that. is there something else?

**Comment by ThetaSigma312** [comment]
Oooh, I see what happened. To avoid further confusion I re-uploaded it as already zipped. Try the link again and download: https://www.dropbox.com/sh/xf8ul6fb7xzheab/AACVbEIkrTCrKfPZ0xkiwj9oa?dl=0

**Comment by garyabart** [comment]
OK, I already have gfxCardstatus.app 2.3 running, is this a different app ?  I trying to lock this computer in to the Integrated only because it locks up in the other graphic modes on this bad G card.

**Comment by ThetaSigma312** [comment]
You have to quit the other one first. It is a different app (it's also versioned under 2.3.1), it won't run along with the other one.

**Comment by garyabart** [comment]
You guys are great, Ill do this later, got to get to a meeting.


g

**Comment by garyabart** [comment]
Downloaded gfx 2.3.1 and quit 2.3.  Dialog box says it can't be opened.  Any ideas? It is in the applications folder etc.

**Comment by ThetaSigma312** [comment]
Would it be possible to send a screenshot of what's going on? You can take one by pressing Command - Shift - 3.

**Comment by garyabart** [comment]
Sure.  
![screen shot 2015-01-18 at 10 12 48 pm](https://cloud.githubusercontent.com/assets/10537591/5795848/5c46d16a-9f5f-11e4-8795-71cb86342c32.png)

**Comment by ThetaSigma312** [comment]
I can reproduce this if I have a copy of gfxcardstatus already running, open Activity Monitor (located in /Applications/Utilities/ folder) and search gfxcardstatus, and if it shows up, quit it with the X near the top left of the window. Then try again with the 2.3.1 version. For the sake of elimination, just delete 2.3 so we can be sure it's not running in any way so as not to interfere with the other one.

**Comment by garyabart** [comment]
OK, I move 2.3 to the trash. Restarted and Opened Activity M, (see screen capture).  Tried to open 2.3.1 and got the same Dialog Box, Cant open.  ??
![screen shot 2015-01-19 at 11 23 25 am](https://cloud.githubusercontent.com/assets/10537591/5804767/440468dc-9fce-11e4-8c4a-85be6a45bef8.png)

**Comment by ThetaSigma312** [comment]
Did you search for it in Activity Monitor? Is it possible you have a copy elsewhere on your computer?

**Comment by garyabart** [comment]
Not in the Activity Monitor, I deleted everything, emptied the trash. Redownloaded the 2.3.1 file and tried to open.  Still says can't open file.  
![screen shot 2015-01-19 at 1 29 20 pm](https://cloud.githubusercontent.com/assets/10537591/5806493/422b213e-9fdf-11e4-9779-3a7a17409c32.png)

**Comment by ThetaSigma312** [comment]
I figured it out, the app folder was set to no access to anyone except my own user account, I've fixed it now. Go ahead and redownload it (https://www.dropbox.com/s/jo8nbs3ixl5liku/gfxCardStatus.zip?dl=0) and try again.

**Comment by garyabart** [comment]
Cant believe it, still wont open. Here is a screen shot of "spotlight search for gfxcardstatus" may be u can see something.

![screen shot 2015-01-19 at 1 54 19 pm](https://cloud.githubusercontent.com/assets/10537591/5806872/04f81bba-9fe3-11e4-9a8c-4ef84621855a.png)

**Comment by ThetaSigma312** [comment]
I went and removed all restrictions to access in folders (stupid of me to forget to remove them in the beginning), so go ahead and delete any version on your computer, and redownload. If it still doesn't work, perhaps I can try and help yo more directly with Skype or something.

**Comment by garyabart** [comment]
I think I need a new link to drop box, I used the last one, no go again.

**Comment by ThetaSigma312** [comment]
Alright, try now.

**Comment by garyabart** [comment]
I got a 404 on dropbox, file moved or deleted.

**Comment by ThetaSigma312** [comment]
Are you sure you're using this link (https://www.dropbox.com/s/ynl57ip4sjsptrc/gfxCardStatus%20%28fixed%29.zip?dl=0) and not one sent to your email? I've updated the comments each time I've changed the link.

**Comment by garyabart** [comment]
That new link worked for download, but the file still will not open.  Cant believe it.

**Comment by ThetaSigma312** [comment]
*headdesk* I'm lost for reasons why. We both have the same architecture, so there shouldn't be any compatibility problems...

Alright, try pressing Command I (as in letter I), on the app, in the window that shows up look for "Sharing & Permissions:" at the bottom left of that section there will be a + sign, press it (you may have to unlock it with the lock icon) and then add your user. After that try opening it.

**Comment by garyabart** [comment]
Did that, screen pic of permissions. closed window etc,  did not open.

![screen shot 2015-01-19 at 2 41 31 pm](https://cloud.githubusercontent.com/assets/10537591/5807487/69985cb4-9fe9-11e4-901d-b480ea17a95c.png)

**Comment by ThetaSigma312** [comment]
Hmm, try doing it to the Contents folder inside the app. Right click the application and select Show Package Contents, and do the same thing to the Contents folder, except before you finish click the gear icon and select "apply to enclosed items". If that doesn't work, I have no idea what is the problem.

**Comment by garyabart** [comment]
Well, were at the end of the rope, tie a knot and hang on I guess.    Still wont open.

**Comment by ThetaSigma312** [comment]
In one of your screenshots I noticed you have Hamachi, can I add you so I can try to screenshare or something?

**Comment by garyabart** [comment]
Iv never used Hamachi, I have Gotomeeting v6.0.  Sure your call.

**Comment by garyabart** [comment]
Oh Logmein is Hamachi, yes I have that.

**Comment by ThetaSigma312** [comment]
I'd prefer Skype, but above all Logmein Hamachi. Hamachi gives a direct link between computers.

**Comment by ThetaSigma312** [comment]
Alright, I made a network named "gfxcardstatus" with the password 123

**Comment by garyabart** [comment]
Only issue is this laptop might lockup with that card issue.  What do you need from me for logmein?

**Comment by ThetaSigma312** [comment]
Add the network I made and I can direct message you.

**Comment by garyabart** [comment]
Sorry, how do i add the network?

**Comment by ThetaSigma312** [comment]
A quick search tells me you have the regular edition of Logmein installed, you'll need Logmein Hamachi (it's free) for this to work. I don't know if the regular version works with the Hamachi I use.

**Comment by ThetaSigma312** [comment]
Or try this: https://secure.logmein.com/hamachi/ih1.asp?lang=en&c=jbeoam0etnyzym543pfpccxe7l9cs6e604kxu98a

**Comment by garyabart** [comment]
I installed Hamachi, tried to join network, said pass word was invalid.

**Comment by codykrieger** [comment]
Can you guys take this conversation over to email please? :)

**Comment by ThetaSigma312** [comment]
@codykrieger  Haha, sorry! I was just thinking this might be spamming you! I've been trying to move this to a instant-messaging place (Hamachi) but it's proving difficult. Moving it asap.

@garyabart Did you try 1234 ?

**Comment by garyabart** [comment]
1234 worked.

g

**Comment by ThetaSigma312** [comment]
Excellent, look out for my message(s).

**Comment by garyabart** [comment]
Hamachi is on the 2010 laptop, I’m reading the emails on my desk top, is that ok ?

**Comment by ThetaSigma312** [comment]
Very well, quick shoot me an email at jared.s.sheppard@icloud.com so I can have your email

**Comment by ThetaSigma312** [comment]
Update (for future peoplez): so my version has some freakish bug that won't let it open on his computer, but @highandfew's original fix can be downloaded here: http://www.sendspace.com/file/xfzn4g and that should work fine

**Comment by ncgmich** [comment]
Dear ThetaSigma312,

Could you re-upload the highandfew patched version somewhere?  That linked is dead.  Urgently needed.  Thank you kindly.

**Comment by ThetaSigma312** [comment]
Unfortunately I don't have highandfew's version on my computer anymore, perhaps try the one I compiled? (https://www.dropbox.com/s/ynl57ip4sjsptrc/gfxCardStatus%20%28fixed%29.zip?dl=0)

**Comment by garyabart** [comment]
Not sure what this email is about but if this helps great.  This file is still working for me on my 2010 MBP.

gary

**Comment by ncgmich** [comment]
Hi.  Unfortunately, I've not been able to get ThetaSigma312's compiled version to launch/execute, but I appreciate his effort and response.

Garyabart, would it be possible for you to re-upload it on a file sharing site?

**Comment by garyabart** [comment]
I sent gfx file via sendthisfile.com  have not used this in a long time.  let me know if it works

gary b

**Comment by ncgmich** [comment]
My e-mail is ncg.michigan@gmail.com for sendthisfile.com purposes.

**Comment by garyabart** [comment]
Sent it.

gary b

**Comment by ncgmich** [comment]
Thank you kindly.  Most appreciated!

**Comment by steveschow** [comment]
One thing I don't understand is why it switches to discrete only after my app closes, rather then switching to Dynamic-switching.

**Comment by xfreece** [comment]
Any chance one could get hold of the file from this comment?
"so my version has some freakish bug that won't let it open on his computer, but @highandfew's original fix can be downloaded here: http://www.sendspace.com/file/xfzn4g and that should work fine"
The sendspace doesn't have the file any longer.

**Comment by garyabart** [comment]
See attached.

**Comment by mrillex** [comment]
can someone send me the file with the working 2.3.1 fix ?

links from 2015 doen´t work anymore...

**Comment by garyabart** [comment]
Hope this helps, let me know.

gary

**Comment by mrillex** [comment]
hi gary!

thanks for the fast reply!

I didn´t see any file attached, was there one ?


thank you! best
martin



--



Mag. Martin Rille
http://rilleworks.com
mr@rilleworks.com

UID ATU67767017 
AT35 1200 0514 1320 0252
BKAUATWW

Kopernikusgasse 9-11/12
A-1060 Wien
M +436507079797

> Am 17.03.2017 um 14:20 schrieb garyabart <notifications@github.com>:
> 
> Hope this helps, let me know.
> 
> gary
> 
> 
> 
> 
> 
> 
>

**Comment by garyabart** [comment]
Yes, it is a zip. Ill try again.

gfxCardStatus.app.zip

**Comment by mrillex** [comment]
hey!

wow thanks, thats so nice - unfortunatelly there was no file in this email - i guess they block files!

could you try with wetransfer.com <http://wetransfer.com/> ?


mr@rilleworks.com



thanks again !


martin
--



Mag. Martin Rille
http://rilleworks.com
mr@rilleworks.com

UID ATU67767017 
AT35 1200 0514 1320 0252
BKAUATWW

Kopernikusgasse 9-11/12
A-1060 Wien
M +436507079797

> Am 17.03.2017 um 21:21 schrieb garyabart <notifications@github.com>:
> 
> Yes, it is a zip. Ill try again.
> 
> gfxCardStatus.app.zip
> 
> 
> 
> 
>

**Comment by garyabart** [comment]
OK, here goes again, I sent it out via Sendthisfile.com  to mr@rilleworks.com <mailto:mr@rilleworks.com>

Let me know.  Believe it or not I had to pull the gfxfile from my trash. You contacted me just in time. I got a new MBP and didn’t need it anymore. Hope it works.

gary

**Comment by mrillex** [comment]
hi gary

thanks this time it worked!

and app works aswell!

thanks, you are the best! (timing is also a good story - pulled from trash) :)

best,
martin



--



Mag. Martin Rille
http://rilleworks.com
mr@rilleworks.com

UID ATU67767017 
AT35 1200 0514 1320 0252
BKAUATWW

Kopernikusgasse 9-11/12
A-1060 Wien
M +436507079797

> Am 18.03.2017 um 20:25 schrieb garyabart <notifications@github.com>:
> 
> OK, here goes again, I sent it out via Sendthisfile.com to mr@rilleworks.com <mailto:mr@rilleworks.com>
> 
> Let me know. Believe it or not I had to pull the gfxfile from my trash. You contacted me just in time. I got a new MBP and didn’t need it anymore. Hope it works.
> 
> gary
> 
>

**Comment by garyabart** [comment]
Great, I'll hold onto it awhile longer. 

G

Sent by Apple Telepathy

**Comment by calmwhiner** [comment]
Hi @garyabart and @mrillex 

I have a early 2011 MBP which i can extend life if i can keep it at integrated graphics..

Any chance for a working link you can share?

I hope it is still in your bin....

Thanks!

**Comment by mrillex** [comment]
I still have it,

but it doesnt work

had a 2010 and a 2011 which autostarted with this tool and now are dead… gfx gets initialized anyway at boot.

this fix should be inside bios or have an alternate bootloader 

or linux


but check for yourself:
https://we.tl/RaxNEJbWUU <https://we.tl/RaxNEJbWUU>


martin

**Comment by calmwhiner** [comment]
Thanks martin for reposting, and @highandfew !

seems to be working now :)

this we transfer link should last a while.

**Comment by steveschow** [comment]
I have incorporated highandfew's fix into my fork and the compiled binary is there to download.  Check it out.

Unfortunately it's not set to integrated-only on boot yet.

Looks like the best fix for 2010 and 2011 mbp users with flakey graphics is to disable entirely the nvidia board, I know of two ways to do this but haven't tried either.  One is a hack out there that hacks the power management kext.  Supposedly it works but it will have to be updated every time apple updates that kext.  Another hack I have seen is a complicated procedure where you make a Linux boot disc and then with Linux you change some data in the EFI somehow which then apparently hides the nVidia card from OSX entrirely.  Supposedly it works but I haven't tried it.

**Comment by iceman60** [comment]
I've tried the second hack on a MBP 17" 2011 it work like a charm!

 Boot with CMD+S
`sudo nvram FA4CE28D-B62F-4C99-9CC3-6815686E30F9:gpu-power-prefs=%01%00%00%00`

**Comment by wagle** [comment]
where does the FA4CE28D-B62F-4C99-9CC3-6815686E30F9 come from?

**Comment by iceman60** [comment]
This is the UUID of this model I guess
You can run : ./nvram-dump 2>&1 | cut -d' ' -f4-

**Comment by steveschow** [comment]
hey this is excellent info thank you!  Its nice to know it can be done directly from the command line in safe mode!  Then its just a matter of making sure to get the correct UUID's for whichever specific mac model is being used and maybe for the nVidia too?  Thanks iceman!

**Comment by steveschow** [comment]
So iceman i tried following a lot of those threads, full of frantic people trying anything to get their machine working...its quite confusing to know for sure what to do.  Am I correct to assume that your one line nvram command is the same result as the long winded and complicated linux solution that is written around?  

Also it looks like most people out there in desperation are 2011 users with AMD discrete graphics, which appears to be more complicated and problematic then the nVidia in some way.  I just want to make sure the above fix would work with my 2010 MBP with nvidia discrete graphics.  gfxCardStatus is working fine for me...but I am on El Capitan and afraid to upgrade to sierra becuase of this, so maybe the nvram fix would let me do that...knock on wood.  Also the nvram fix will be on at boot, while gfxCardStatus has to be manually switched to integrated-only every time I reboot.  Also OSX still seems to need to switch to discrete briefly when exiting apps, before gfxCardStatus switches it back to integrated.  Theoretically, the nvram trick avoids that issue as well.  I'm definitely keen to try it out, but since everyone on those threads is using AMD's....and by the way having lots of problems still too...I'm still a little afraid to try it

**Comment by steveschow** [comment]
That gpu-switch tool looks kind of interesting as an alternative solution as well...perhaps using that on boot will be the best bet for me.  I pretty much never use my 2010 in dynamic mode.  if an app won't work with integrated graphics, then I just find a different app

**Comment by iceman60** [comment]
Sorry, this seems to be a GUID (EFI manufacturing unique id, not the UUID) associated with others MBP model
here is another thread with nVidia (MBP 2013) discrete card : https://gist.github.com/0xbb/974999591da4b1b2635c
another with MBP 2014 and GT750M : https://github.com/ah-/gmux-scripts/issues/1

The only things I'm sure is for my model running this one line command in Safe mode do the job!
Did you try?
Now I'm trying to get the GUID for an iMac12,2 with a faulty AMD 6970M...

**Comment by steveschow** [comment]
yea, the nvram hack doesn't work on my mac.  Period.  After wasting a lot of time on this yesterday I am convinced that hack is great for the MBP's with AMD, but not for nVidia.  Also, it may  not be the best solution afterall to disable the discrete graphics (see below).

Also it may be different for linux users then it is for OSX users.  gpu-switch, for example, is really not appropriate for OSX.

At this point I have decided to get the capacitor replaced on my MBP logicboard, which is the culprit of the problem for 2010 MBP's.  It will cost a few hundred bucks and solve the whole problem.   In the meantime, I have actually stopped using gfxCardStatus 2.4.4i, which works fine, but there is another solution I am trying for a while that doesn't disable the discrete graphics, it just slows it down enough to avoid the problem caused by the flakey capacitor.  

https://github.com/julian-poidevin/MBPMid2010_GPUFix

The above helps my MBP, but doesn't help the ones with AMD gpu's, they will need to use the nvram hack I guess.

**Comment by informationquestions** [comment]
Does anyone have this file? The we transfer link is expired :(

> I still have it, but it doesnt work had a 2010 and a 2011 which autostarted with this tool and now are dead… gfx gets initialized anyway at boot. this fix should be inside bios or have an alternate bootloader or linux but check for yourself: https://we.tl/RaxNEJbWUU <https://we.tl/RaxNEJbWUU> martin
> […](#)



> I still have it, but it doesnt work had a 2010 and a 2011 which autostarted with this tool and now are dead… gfx gets initialized anyway at boot. this fix should be inside bios or have an alternate bootloader or linux but check for yourself: https://we.tl/RaxNEJbWUU <https://we.tl/RaxNEJbWUU> martin
> […](#)

**Comment by informationquestions** [comment]
> Thanks martin for reposting, and @highandfew !
> 
> seems to be working now :)
> 
> this we transfer link should last a while.

Does anyone have this file? The we transfer link is expired :(

**Comment by informationquestions** [comment]
> yea, the nvram hack doesn't work on my mac. Period. After wasting a lot of time on this yesterday I am convinced that hack is great for the MBP's with AMD, but not for nVidia. Also, it may not be the best solution afterall to disable the discrete graphics (see below).
> 
> Also it may be different for linux users then it is for OSX users. gpu-switch, for example, is really not appropriate for OSX.
> 
> At this point I have decided to get the capacitor replaced on my MBP logicboard, which is the culprit of the problem for 2010 MBP's. It will cost a few hundred bucks and solve the whole problem. In the meantime, I have actually stopped using gfxCardStatus 2.4.4i, which works fine, but there is another solution I am trying for a while that doesn't disable the discrete graphics, it just slows it down enough to avoid the problem caused by the flakey capacitor.
> 
> https://github.com/julian-poidevin/MBPMid2010_GPUFix
> 
> The above helps my MBP, but doesn't help the ones with AMD gpu's, they will need to use the nvram hack I guess.



> Great, I'll hold onto it awhile longer. G Sent by Apple Telepathy
> […](#)

Does anyone have this file? The we transfer link is expired :(

**Comment by informationquestions** [comment]
I also found this link for a different file:

https://mac.softpedia.com/get/System-Utilities/gfxCardStatus.shtml

it says 2.4.4i but when you download it gives you the option to download 2.4.4i for 2011 MacBook Pro or 2.4.2i for 2010 MacBook Pro, anyone know if it makes a difference?

**Comment by garyabart** [comment]
I still have the file, see attached zip.  Hope it works.On Oct 7, 2018, at 1:40 AM, informationquestions <notifications@github.com> wrote:Does anyone have this file? The we transfer link is expired :(
I still have it, but it doesnt work had a 2010 and a 2011 which autostarted with this tool and now are dead… gfx gets initialized anyway at boot. this fix should be inside bios or have an alternate bootloader or linux but check for yourself: https://we.tl/RaxNEJbWUU https://we.tl/RaxNEJbWUU martin
…

I still have it, but it doesnt work had a 2010 and a 2011 which autostarted with this tool and now are dead… gfx gets initialized anyway at boot. this fix should be inside bios or have an alternate bootloader or linux but check for yourself: https://we.tl/RaxNEJbWUU https://we.tl/RaxNEJbWUU martin
…
