### ISSUE TITLE
gfxCardStatus says I have an unsupported machine

### ISSUE THREAD

**Issue by MadsHelmer** [codykrieger/gfxCardStatus#137]
Hi

I have just installed the new Mavericks for my mac, and now my gfxcardsstatus won't work... Any help!? It says that my machine is unsupported...

**Comment by stefanoferruggiara** [comment]
And then? How we can remove it? Cause i have the same problem caused by time machine backup.. remove after GFX... and nothing.. same message everytime i start a new session with my mac from switchoff.
