### ISSUE TITLE
Can't switch to integrated when gfxCardStatus is running

### ISSUE THREAD

**Issue by NeverADullMoment** [codykrieger/gfxCardStatus#168]
OK, I wasn't expecting this.  I was running Firefox 32, OSX Mavericks, and gfxCardStatus v2.3, reading the HowTo's.  I was trying to get the Dependencies list to show up, finally figured out how to do that.  Specifically, I went from Integrated Only, to Dynamic Switching, then to Discrete Only.  The Dependencies list showed up.  gfxCardStatus was the only app in the list, and so to switch out of Discrete Only, I had to quit gfxCardStatus first.  That doesn't sound right to me...

**Comment by JonathanWexler** [comment]
The issue is happening on MacOS

![screen shot 2016-11-19 at 11 13 52 pm](https://cloud.githubusercontent.com/assets/1715391/20460368/dcab7cd4-aead-11e6-848c-517d1ca45164.png)

**Comment by tommyjcarpenter** [comment]
I am also getting "gfxcardstatus" can't switch because of "gfxcardstatus"... seems a bit incestuous.

**Comment by dkmooers** [comment]
I'm also unable to switch to Integrated because "gfxCardStatus" is running, same as @JonathanWexler. Ideas? Trying to avoid using the discrete GPU in my 2011 MBP 15" because it's dying and giving me horrible screen issues and random restarts.

**Comment by JonathanWexler** [comment]
Unfortunately @tommyjcarpenter, this was an ongoing problem, shutting down my machine at critical moments, so I bought a new one. Apple should ultimately be responsible for faulty hardware, but I don’t see gfxcardstatus working for that model in the same way anymore.
