### ISSUE TITLE
dynamic switching with exceptions request feature

### ISSUE THREAD

**Issue by boza111** [codykrieger/gfxCardStatus#186]
Would it be possible to add a customisable list of apps which will run on the integrated gpu?

Chrome would be a good example to add to this ignore list. When chrome is run by the user it will not trigger a dynamic switch. If VLC is run after chrome it will trigger the dynamic switch as usual until it is closed again.

Is this technically possible?

**Comment by codykrieger** [comment]
Unfortunately, no, this is not technically possible.

**Comment by boza111** [comment]
Thanks for the reply Cody. Little snitch is the worst offender as it is always open and really doesn't require the dedicated gpu.

Thanks for this amazing app!
