### ISSUE TITLE
Lockups after Yosemite upgrade

### ISSUE THREAD

**Issue by ispcolohost** [codykrieger/gfxCardStatus#187]
Hello, I've been using gfxCardStatus since about Oct 2012 on an MBPr 15.  Unfortunately I don't recall which OS version I started out with, but I've gone through several upgrades since then without issue.  After installing the latest, Yosemite, I've been encountering lockups when using gfxCardStatus to manually switch states, or lock to integrated.

I was curious if anyone else is running into this?  I'm going to run with it disabled for the time being and see if the lockups continue and can report back.  I do also run SwitchResX to allow me to use 2048x1280 resolution but it hasn't had any issues and I've used both apps all along.

Thanks

**Comment by codykrieger** [comment]
Can you describe what you mean by "lockups?" There's no problem with gfxCardStatus and Yosemite that I'm aware of. Sometimes resetting your PRAM helps with strange issues like this: http://support.apple.com/kb/PH18761

**Comment by tarix** [comment]
@ispcolohost 
Based on my personal testing (Mid 2012 Retina MBP) Yosemite itself locks up, it's actually a kernel panic in the graphics drivers, regardless of having gfxCardStatus installed or not. Resetting the PRAM and the SMC hasn't helped any but having gfxCardStatus force to Integrated only mode has helped a lot.

I feel like this article covers the situation fairly well:
http://www.macnn.com/articles/14/11/04/several.support.threads.discussing.issue.related.to.gpu.switching/
