### ISSUE TITLE
Can't switch to Integrated on Yosemite (2011 MacBook Pro w/ probable GPU issues)

### ISSUE THREAD

**Issue by tyhenry** [codykrieger/gfxCardStatus#188]
Hi - I've tried gfxCardStatus 2.3 and 1.8.1 - both have a similar issue:
I can open the app and select Integrated Only; the checkmark moves to Integrated but the menubar icon stays on "d" and the GPU is still listed as "AMD Radeon HD 6490M".
This is on a 2011 MacBook Pro with (what appears to be) GPU issues.  But the kernel extensions are all in place.  Any thoughts?
![screen shot 2015-01-19 at 3 41 08 pm](https://cloud.githubusercontent.com/assets/8344718/5808020/dfea234a-9ff6-11e4-9b10-21ed225ed925.png)

**Comment by codykrieger** [comment]
It's hard to say. gfxCardStatus' behavior on machines with busted hardware is completely unpredictable. :/

You could try resetting your PRAM, which sometimes helps with odd issues like this: http://support.apple.com/kb/PH18761
