### ISSUE TITLE
gfxCardStatus won't launch on Yosemite/MBP Mid 2010

### ISSUE THREAD

**Issue by nielsoledam** [codykrieger/gfxCardStatus#189]
Hi Cody

Just downloaded gfxCardStatus on my 13" Mid 2010 Macbook Pro running the newest Yosemite (10.10.1).

But the application won't launch – it just says:
"You are using a system that gfxCardStatus does not support."... etc.

Do you know what the issue might be?

My Macbook Pro has NVIDIA GeForce 320M 256 MB, so I do think it should be supported by the app.

Niels Ole Dam

**Comment by codykrieger** [comment]
> My Macbook Pro has NVIDIA GeForce 320M 256 MB

No it doesn't. 13" MacBook Pros do not have a discrete GPU. You only have the Intel integrated GPU.

**Comment by nielsoledam** [comment]
Oh, sorry for the mistake!
(And thanks for a swift answer!)
:-)
Niels
