### ISSUE TITLE
10.10 Preferences pane doesn't show any options

### ISSUE THREAD

**Issue by nguillermin** [codykrieger/gfxCardStatus#191]
Pretty much, fresh install of 10.10 (just got this computer off ebay) on a Late 2011 MacbookPro8,2. Open the preference pane and all I get is this:
![Whole lot of nothing](http://i.imgur.com/ZSRCZ8O.png)
Checked Console for some logs, found this:

	2/7/15 9:08:00.825 PM gfxCardStatus[1302]: An uncaught exception was raised
	2/7/15 9:08:00.829 PM gfxCardStatus[1302]: -[GeneralPreferencesViewController loadView] could not load the "GeneralPreferencesView" nib.
	2/7/15 9:08:01.125 PM gfxCardStatus[1302]: (
		0   CoreFoundation                      0x00007fff8e66266c __exceptionPreprocess + 172
		1   libobjc.A.dylib                     0x00007fff93ac776e objc_exception_throw + 43
		2   CoreFoundation                      0x00007fff8e66251d +[NSException raise:format:] + 205
		3   AppKit                              0x00007fff94f32a46 -[NSViewController loadView] + 831
		4   gfxCardStatus                       0x000000010e201f23 gfxCardStatus + 16163
		5   AppKit                              0x00007fff9519d417 -[NSViewController _loadViewIfRequired] + 75
		6   AppKit                              0x00007fff94e6d9b1 -[NSViewController view] + 30
		7   gfxCardStatus                       0x000000010e2030cc gfxCardStatus + 20684
		8   gfxCardStatus                       0x000000010e202a4f gfxCardStatus + 19023
		9   gfxCardStatus                       0x000000010e207656 gfxCardStatus + 38486
		10  libsystem_trace.dylib               0x00007fff94473cd7 _os_activity_initiate + 75
		11  AppKit                              0x00007fff94f7db71 -[NSApplication sendAction:to:from:] + 452
		12  AppKit                              0x00007fff94f97cbe -[NSMenuItem _corePerformAction] + 382
		13  AppKit                              0x00007fff94f979dc -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
		14  libsystem_trace.dylib               0x00007fff94473cd7 _os_activity_initiate + 75
		15  AppKit                              0x00007fff94fe54e0 -[NSMenu performActionForItemAtIndex:] + 131
		16  AppKit                              0x00007fff94fe5446 -[NSMenu _internalPerformActionForItemAtIndex:] + 35
		17  AppKit                              0x00007fff94fe5292 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
		18  AppKit                              0x00007fff94f8d5db NSSLMMenuEventHandler + 724
		19  HIToolbox                           0x00007fff9622598c _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1260
		20  HIToolbox                           0x00007fff96224dce _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 386
		21  HIToolbox                           0x00007fff962398f6 SendEventToEventTarget + 40
		22  HIToolbox                           0x00007fff9626ef25 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 428
		23  HIToolbox                           0x00007fff962a264d SendMenuCommandWithContextAndModifiers + 59
		24  HIToolbox                           0x00007fff962a25f4 SendMenuItemSelectedEvent + 188
		25  HIToolbox                           0x00007fff962a24c6 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
		26  HIToolbox                           0x00007fff963d2481 _ZL19PopUpMenuSelectCoreP8MenuData5PointdS1_tjPK4RecttjS4_S4_PK14__CFDictionaryPK10__CFStringPP13OpaqueMenuRefPt + 1877
		27  HIToolbox                           0x00007fff963d1604 _ZL26_HandlePopUpMenuSelection8P13OpaqueMenuRefP14OpaqueEventRefj5PointtjPK4RecttS6_S6_PK14__CFDictionaryPK10__CFStringPS0_Pt + 633
		28  HIToolbox                           0x00007fff963d179b _HandlePopUpMenuSelectionWithDictionary + 287
		29  AppKit                              0x00007fff94fe40bd _NSSLMPopUpCarbonMenu3 + 5810
		30  AppKit                              0x00007fff94fe29ef _NSPopUpCarbonMenu3 + 153
		31  AppKit                              0x00007fff94fe2751 -[NSCarbonMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 350
		32  AppKit                              0x00007fff953c4be8 +[NSStatusBarButtonCell popupStatusBarMenu:inRect:ofView:withEvent:] + 682
		33  AppKit                              0x00007fff950994dd -[NSStatusBarButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 159
		34  AppKit                              0x00007fff94fdf899 -[NSControl mouseDown:] + 714
		35  AppKit                              0x00007fff954dda18 -[NSWindow _reallySendEvent:] + 12721
		36  AppKit                              0x00007fff94f6416e -[NSWindow sendEvent:] + 446
		37  AppKit                              0x00007fff95054fc1 -[NSStatusBarWindow sendEvent:] + 242
		38  AppKit                              0x00007fff94f16451 -[NSApplication sendEvent:] + 4183
		39  AppKit                              0x00007fff94da2608 -[NSApplication run] + 711
		40  AppKit                              0x00007fff94d8da14 NSApplicationMain + 1832
		41  gfxCardStatus                       0x000000010e1ffce4 gfxCardStatus + 7396
		42  ???                                 0x0000000000000002 0x0 + 2
	)
	2/7/15 9:08:14.816 PM gfxCardStatus[1302]: -[GeneralPreferencesViewController loadView] could not load the "GeneralPreferencesView" nib.
	2/7/15 9:08:14.833 PM gfxCardStatus[1302]: (
		0   CoreFoundation                      0x00007fff8e66266c __exceptionPreprocess + 172
		1   libobjc.A.dylib                     0x00007fff93ac776e objc_exception_throw + 43
		2   CoreFoundation                      0x00007fff8e66251d +[NSException raise:format:] + 205
		3   AppKit                              0x00007fff94f32a46 -[NSViewController loadView] + 831
		4   gfxCardStatus                       0x000000010e201f23 gfxCardStatus + 16163
		5   AppKit                              0x00007fff9519d417 -[NSViewController _loadViewIfRequired] + 75
		6   AppKit                              0x00007fff94e6d9b1 -[NSViewController view] + 30
		7   gfxCardStatus                       0x000000010e2030cc gfxCardStatus + 20684
		8   gfxCardStatus                       0x000000010e203042 gfxCardStatus + 20546
		9   AppKit                              0x00007fff954928e9 -[NSToolbarButton sendAction:to:] + 75
		10  AppKit                              0x00007fff9504091a -[NSToolbarItemViewer mouseDown:] + 4981
		11  AppKit                              0x00007fff954dda18 -[NSWindow _reallySendEvent:] + 12721
		12  AppKit                              0x00007fff94f6416e -[NSWindow sendEvent:] + 446
		13  AppKit                              0x00007fff94f16451 -[NSApplication sendEvent:] + 4183
		14  AppKit                              0x00007fff94da2608 -[NSApplication run] + 711
		15  AppKit                              0x00007fff94d8da14 NSApplicationMain + 1832
		16  gfxCardStatus                       0x000000010e1ffce4 gfxCardStatus + 7396
		17  ???                                 0x0000000000000002 0x0 + 2
	)
	2/7/15 9:08:19.436 PM gfxCardStatus[1302]: -[AdvancedPreferencesViewController loadView] could not load the "AdvancedPreferencesView" nib.
	2/7/15 9:08:19.438 PM gfxCardStatus[1302]: (
		0   CoreFoundation                      0x00007fff8e66266c __exceptionPreprocess + 172
		1   libobjc.A.dylib                     0x00007fff93ac776e objc_exception_throw + 43
		2   CoreFoundation                      0x00007fff8e66251d +[NSException raise:format:] + 205
		3   AppKit                              0x00007fff94f32a46 -[NSViewController loadView] + 831
		4   AppKit                              0x00007fff9519d417 -[NSViewController _loadViewIfRequired] + 75
		5   AppKit                              0x00007fff94e6d9b1 -[NSViewController view] + 30
		6   gfxCardStatus                       0x000000010e2030cc gfxCardStatus + 20684
		7   gfxCardStatus                       0x000000010e203042 gfxCardStatus + 20546
		8   AppKit                              0x00007fff954928e9 -[NSToolbarButton sendAction:to:] + 75
		9   AppKit                              0x00007fff9504091a -[NSToolbarItemViewer mouseDown:] + 4981
		10  AppKit                              0x00007fff954dda18 -[NSWindow _reallySendEvent:] + 12721
		11  AppKit                              0x00007fff94f6416e -[NSWindow sendEvent:] + 446
		12  AppKit                              0x00007fff94f16451 -[NSApplication sendEvent:] + 4183
		13  AppKit                              0x00007fff94da2608 -[NSApplication run] + 711
		14  AppKit                              0x00007fff94d8da14 NSApplicationMain + 1832
		15  gfxCardStatus                       0x000000010e1ffce4 gfxCardStatus + 7396
		16  ???                                 0x0000000000000002 0x0 + 2
	)
	2/7/15 9:09:05.661 PM gfxCardStatus[1302]: -[GeneralPreferencesViewController loadView] could not load the "GeneralPreferencesView" nib.
	2/7/15 9:09:05.663 PM gfxCardStatus[1302]: (
		0   CoreFoundation                      0x00007fff8e66266c __exceptionPreprocess + 172
		1   libobjc.A.dylib                     0x00007fff93ac776e objc_exception_throw + 43
		2   CoreFoundation                      0x00007fff8e66251d +[NSException raise:format:] + 205
		3   AppKit                              0x00007fff94f32a46 -[NSViewController loadView] + 831
		4   gfxCardStatus                       0x000000010e201f23 gfxCardStatus + 16163
		5   AppKit                              0x00007fff9519d417 -[NSViewController _loadViewIfRequired] + 75
		6   AppKit                              0x00007fff94e6d9b1 -[NSViewController view] + 30
		7   gfxCardStatus                       0x000000010e2030cc gfxCardStatus + 20684
		8   gfxCardStatus                       0x000000010e203042 gfxCardStatus + 20546
		9   AppKit                              0x00007fff954928e9 -[NSToolbarButton sendAction:to:] + 75
	10  AppKit                              0x00007fff9504091a -[NSToolbarItemViewer mouseDown:] + 4981
	11  AppKit                              0x00007fff954dda18 -[NSWindow _reallySendEvent:] + 12721
	12  AppKit                              0x00007fff94f6416e -[NSWindow sendEvent:] + 446
	13  AppKit                              0x00007fff94f16451 -[NSApplication sendEvent:] + 4183
	14  AppKit                              0x00007fff94da2608 -[NSApplication run] + 711
	15  AppKit                              0x00007fff94d8da14 NSApplicationMain + 1832
	16  gfxCardStatus                       0x000000010e1ffce4 gfxCardStatus + 7396
	17  ???                                 0x0000000000000002 0x0 + 2
    )

**Comment by codykrieger** [comment]
No one else is having this problem on 10.10...try re-downloading maybe?

**Comment by nguillermin** [comment]
That fixed it. Cool.
