### ISSUE TITLE
“gfxCardStatus” is damaged and cannot be opened

### ISSUE THREAD

**Issue by acanada** [codykrieger/gfxCardStatus#192]
I have downloaded gfxCardStatus and moved to Applications folder. When I try to start it, all I get is 
“gfxCardStatus” is damaged and cannot be opened, you should move it to the trash (not literally, this was translated from spanish message).
I have download it from http://gfx.io/downloads/gfxCardStatus-2.3.zip

Could you please tell me what can I do?
I really need this app   :-(

Best regards,
Andrés

**Comment by codykrieger** [comment]
No one else is having this problem...what unarchiving tool are you using to extract the archive? The built-in OS X Archive Utility? The Unarchiver?

**Comment by codykrieger** [comment]
Also:

- What OS X version are you running?
- What browser are you downloading the archive with?

**Comment by acanada** [comment]
Sorry about this, it was the security/privacy option “Allow apps downloaded from”, I had "Mac App Store” checked (since it was a new OS installed and the first app that I was installing was this).

I changed to “Anywhere” and everything works perfect.

Sorry but the message that Macs gives in this case is everything but intuitive.

Best regards

Andrés

On 17 Feb 2015, at 08:30, Cody Krieger <notifications@github.com<mailto:notifications@github.com>> wrote:


Also:

  *   What OS X version are you running?
  *   What browser are you downloading the archive with?

**Comment by codykrieger** [comment]
"Anywhere" is a bit too lenient. You want the "Mac App Store and identified developers" option.
