### ISSUE TITLE
feature request - workaround for damaged discrete graphics card

### ISSUE THREAD

**Issue by nobbycat** [codykrieger/gfxCardStatus#194]
Hello, 
Thank you for your very useful tool. it has saved my macbook pro from the dustbin, due to the famous discrete graphics card hardware fault which causes kernel crashes. (I think its a damaged BGA connections due )

So I use gfxCardStatus to control access to the discrete gfx and that allows the laptop to function correctly...

By adding an advanced switch to allow forced/fixed integrated only (even if chrome, vmware, etc activate the discrete, it would stop my macbook from crashing.

There must be many people like me with a 2012 series mbp with the same problem.

Kind Regards
/giles

**Comment by codykrieger** [comment]
Just activate Integrated Only before you launch Chrome or VMware.
