### ISSUE TITLE
gfxcardstatus issue

### ISSUE THREAD

**Issue by libertadvives** [codykrieger/gfxCardStatus#195]
Hi.

I've been using gfxcardstatus for a long time on OSX Lion 10.7.5 (MBP late 2011). You really saved my life.

But I've been experience this issue for last few weeks:

- If I run “integrated only” right after the start up, my computer freezes. I have to wait for a while before doing it, but even like that sometimes it freezes anyway (around 30 seconds after run it).

- This happen even when there is not software running.

Fortunately, Apple finally lunched a Repair Extension Program for Video Issues (https://www.apple.com/support/macbookpro-videoissues/) but for now I can't be without my computer for the 5-7 days it takes the repair.

Hope you can help me.

Bests from Mexico and sorry for my English...

**Comment by codykrieger** [comment]
I'm sorry, you'll have to get your machine repaired. :( The issue you're seeing is very likely a symptom of the hardware issues you've got.

**Comment by libertadvives** [comment]
Ok. It seems I will have to keep pushing my MBP to a "melting point" to restart on integrated only for a while. Thanks for replying...
