### ISSUE TITLE
Silent exit of the app v2.3

### ISSUE THREAD

**Issue by askaliuk** [codykrieger/gfxCardStatus#196]
My setup:
10.8.5, 15-inch, early 2013.

Has 2 video cards:
* Intel HD Graphics 4000 512 MB
* NVIDIA GeForce GT 650M

{code}
~/Applications$ open -a gfxCardStatus.app
~/Applications$ 
{/code}

Can i check logs somewhere or something?

**Comment by codykrieger** [comment]
It doesn't silently exit, ever. It either:

- Crashed, in which case you'd see logs in Console.app
- Opened and is displaying a modal dialog telling you your machine is unsupported
- Opened successfully, and is running in your menu bar

When you `open` a .app it's generally not expected for it to run in the foreground. If you run the binary inside the .app directly (`./gfxCardStatus.app/Contents/MacOS/gfxCardStatus`), it will run in the foreground.

**Comment by askaliuk** [comment]
I don't see any logs in console.

```
/Applications$ sudo ./gfxCardStatus.app/Contents/MacOS/gfxCardStatus
Password:
dyld: Library not loaded: @executable_path/../Frameworks/ReactiveCocoa.framework/ReactiveCocoa
  Referenced from: /Applications/./gfxCardStatus.app/Contents/MacOS/gfxCardStatus
  Reason: no suitable image found.  Did find:
	/Applications/./gfxCardStatus.app/Contents/MacOS/../Frameworks/ReactiveCocoa.framework/ReactiveCocoa: file too short
	/Applications/gfxCardStatus.app/Contents/MacOS/../Frameworks/ReactiveCocoa.framework/ReactiveCocoa: file too short
```

**Comment by codykrieger** [comment]
That would definitely manifest in a crash log. Probably in Console.app in the left sidebar under User Diagnostic Reports.

Usually that message means that whatever you used to unzip gfxCardStatus mangled the app bundle. Try extracting with OS X's built in Archive Utility instead of whatever you used, and/or re-download a fresh copy of the zip file to make sure it wasn't corrupted or something.

**Comment by codykrieger** [comment]
(Also, no need to run under sudo; in fact that's probably a bad thing.)

**Comment by askaliuk** [comment]
Looks like the archive was broken. 
```
/Applications$ ./gfxCardStatus.app/Contents/MacOS/gfxCardStatus
```
works now ok. Thanks for help!

**Comment by codykrieger** [comment]
You bet!
