### ISSUE TITLE
2013 Early Macbook Pro how to disable the nvidia graphics card ?

### ISSUE THREAD

**Issue by Fazelesswhite** [codykrieger/gfxCardStatus#197]
Hey guys! 

My question is quite simple, I just want to disable the nvidia 650m found in the 2013 early MBP, it's faulty and I don't use much graphic intensive apps.. I can't get this fixed since they're asking to replace the logic board which is not a viable option for me. If anyone can guide me on how to use on the integrated intel GPU, it would be awesome! :D 

Thanks !

**Comment by codykrieger** [comment]
Issues are not an appropriate vessel for arbitrary discussions; they're for reporting issues with gfxCardStatus.
