### ISSUE TITLE
dual gpu's not recognized

### ISSUE THREAD

**Issue by ecblanks** [codykrieger/gfxCardStatus#198]
Hi, I've been using your software for over a year now without issue (thanks!), but suddenly it is telling me that my system does not have dual gpu's (it does).  It is a mid-2010 15" MBP. 
Thanks,
Carlton

**Comment by codykrieger** [comment]
Try resetting your PRAM. That usually fixes it.

**Comment by ecblanks** [comment]
Thanks, will do.
