### ISSUE TITLE
Graphics Processor Choice Doesn't "Stick"

### ISSUE THREAD

**Issue by lybanon** [codykrieger/gfxCardStatus#200]
15-inch Mid 2010 MacBook Pro, OS X 10.10.3, latest version of gfxCardStatus

If I choose "Integrated Only," sometimes the system (presumably) switches to the discrete GPU on its own.  When that happens, the gfxCardStatus menu bar indicator shows "Discrete Only."  I can switch back to Integrated Only manually unless some program is running that prevents it.

**Comment by codykrieger** [comment]
Dupe of #107.
