### ISSUE TITLE
sleep after 'integrated only' leads to inconsistent mode/display

### ISSUE THREAD

**Issue by sparr** [codykrieger/gfxCardStatus#201]
Using OSX 10.9.5 I often use the 'integrated only' setting to conserve battery. If my machine goes to sleep (and possibly some other criteria) then later when I wake it up it will say it's in 'dynamic switching' mode, but it won't switch to the dedicated graphics card when I run a game or plug in an external monitor. I have to click 'integrated only' again (to switch "out" of dynamic switching mode) then click 'dynamic switching', then it works fine.

**Comment by codykrieger** [comment]
Dupe of #109.
