### ISSUE TITLE
gfxCardStatus impossible remove

### ISSUE THREAD

**Issue by stefanoferruggiara** [codykrieger/gfxCardStatus#203]
Hi Cody, listen.. i have installed on my old macbookpro 15" your gfxCardStatus,, and work perfect.. yesterday i sell and first i backup all.
I buy a Macbook pro mid 2012 and backup all from time machine.
I removed from application folder gfxCardStatus, but when a restart.. appear a message as you see in attached. 
I clean all in Library/preferences/...
I remove all file with app cleaner.. but.. nothing..
Any suggest?
Thanks for fast reply.
Stefano
![screenshot 2015-06-11 16 24 32](https://cloud.githubusercontent.com/assets/12846616/8109597/d66249f2-1057-11e5-9881-15ddf91b2218.png)

**Comment by codykrieger** [comment]
If you move gfxCardStatus to the trash and empty the trash, there's no possible way for gfxCardStatus to start up. If it's still starting up after you've done this, then you have another copy of it somewhere on your Mac.
