### ISSUE TITLE
Not true in Yosemite 10.10.3. -- "Integrated Only: Forces the more battery-friendly graphics on and disallows automatic switching."

### ISSUE THREAD

**Issue by lowellwa** [codykrieger/gfxCardStatus#204]
If I pick "Integrated Only" it switches as expected (unless there are dependencies), and then it "randomly" switches back to "d". For example, in GoToMeeting, it always switches to "d".

Would a US$100 donation help?

**Comment by codykrieger** [comment]
I think you're looking for #103. As much as I'd love to accept a $100 donation, I don't really have the time to investigate a proper fix for the issue.

**Comment by codykrieger** [comment]
Sorry, #107, not #103.
