### ISSUE TITLE
How do I remove gfxCardStatus from my MBP?

### ISSUE THREAD

**Issue by gdejager** [codykrieger/gfxCardStatus#205]
I installed gfxCardStatus in an attempt to halt frequent crashes by investigating graphics card status. What i get from the app is a message with "Your are using a system that gfxCardStatus does not support". I have a 2013 Retina 15.

So I'd like to just remove the app because it flashes that message every time I restart (after a crash). I can't remove because I can't find it! A search produces the app (even though it doesn't show up in the Applications folder. But when found, I can't do anything but run it. No control panel, no indication of where it might be stored. Help?

G

**Comment by codykrieger** [comment]
Assuming by "search" you mean you're using Spotlight, you can hit Cmd-R on gfxCardStatus in the results list, which will reveal it in Finder. Then you can just send it to the Trash, like any other Mac app.

**Comment by gdejager** [comment]
Not sure how I didn’t know about cmd-R. That worked. Thanks!

From: Cody Krieger
Reply-To: codykrieger/gfxCardStatus
Date: Wednesday, July 15, 2015 at 7:18 AM
To: codykrieger/gfxCardStatus
Cc: Greg DeJager
Subject: Re: [gfxCardStatus] How do I remove gfxCardStatus from my MBP? (#205)


Assuming by "search" you mean you're using Spotlight, you can hit Cmd-R on gfxCardStatus in the results list, which will reveal it in Finder. Then you can just send it to the Trash, like any other Mac app.
