### ISSUE TITLE
Switching doesn't work on Yosemite 10.10.4

### ISSUE THREAD

**Issue by kourindouhime** [codykrieger/gfxCardStatus#206]
Hello. After updating to 10.10.4, forced discrete gpu switching doesn't work anymore. How can I debug this?

<img width="266" alt="screen shot 2558-07-18 at 12 08 57 pm" src="https://cloud.githubusercontent.com/assets/625899/8760429/f3939d54-2d45-11e5-9457-513ea7888c53.png">

Thank you!

**Comment by codykrieger** [comment]
Maybe you're seeing something like this behavior? https://github.com/codykrieger/gfxCardStatus/issues/103

I haven't seen any other reports of this.
