### ISSUE TITLE
UnsupportedMachine after Security Update 2015-005

### ISSUE THREAD

**Issue by LPforget** [codykrieger/gfxCardStatus#207]
I have mac OS X 10.8.5 (12F2542) and after i installed the Security Update 2015-005 gfxCardStatus will not start anymore and gives me the error UnsupportedMachine.

please help rapidly as my machine crashes within an hour when not in Integrated mode and apple doesn't support my MacBook Pro 15 inches, mid-2010.

**Comment by codykrieger** [comment]
Resetting your NVRAM will probably help: https://support.apple.com/en-us/HT204063
