### ISSUE TITLE
gfxCardStatus will not open

### ISSUE THREAD

**Issue by Danyaga** [codykrieger/gfxCardStatus#208]
Hi, on my new macbook 15" (mid 2015 with 10.10.4) gfxCardStatus just will open up.

I click on in and nothing happens, no bar icon or anything other.

Here the crash report from Console:

Process:               gfxCardStatus [1302]
Path:                  /Users/USER/Desktop/gfxCardStatus.app/Contents/MacOS/gfxCardStatus
Identifier:            com.codykrieger.gfxCardStatus
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           gfxCardStatus [1302]
User ID:               501

Date/Time:             2015-07-24 14:18:42.312 +0200
OS Version:            Mac OS X 10.10.4 (14E46)
Report Version:        11
Anonymous UUID:        02090566-AC1D-4C1F-9566-0A8B765EE890

Sleep/Wake UUID:       66CB19EB-2A13-4C60-98E2-D4830EDCBD54

Time Awake Since Boot: 7400 seconds
Time Since Wake:       1100 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/ReactiveCocoa.framework/ReactiveCocoa
  Referenced from: /Users/USER/Desktop/gfxCardStatus.app/Contents/MacOS/gfxCardStatus
  Reason: no suitable image found.  Did find:
	/Users/daniel/Desktop/gfxCardStatus.app/Contents/MacOS/../Frameworks/ReactiveCocoa.framework/ReactiveCocoa: file too short
	/Users/daniel/Desktop/gfxCardStatus.app/Contents/MacOS/../Frameworks/ReactiveCocoa.framework/ReactiveCocoa: file too short

Binary Images:
    0x7fff6b4bf000 -     0x7fff6b4f5837  dyld (353.2.1) <72A99D0F-0B56-3938-ABC5-67A0F33757C4> /usr/lib/dyld
    0x7fff9398f000 -     0x7fff93b3fff3  com.apple.QuartzCore (1.10 - 361.19) <F815B60E-75E3-3263-BE93-27A49882CF58> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore

**Comment by codykrieger** [comment]
The app is damaged; it must have been corrupted when it was extracted. If you're using The Unarchiver try using the standard built-in OS X Archive Utility to extract the app from the .zip file.

**Comment by Danyaga** [comment]
Nice, that definitely was the problem.

I used to extract zip with iZip, bit this one needs to be extracted with built-in OS X Archive Utility.

Thx a lot.

**Comment by codykrieger** [comment]
You bet—thanks for attaching the crash log! Makes it much easier to diagnose without all of the back-and-forth. ;)
