### ISSUE TITLE
Getting a gfcardstatus crash after installing new version

### ISSUE THREAD

**Issue by mschipperheyn** [codykrieger/gfxCardStatus#209]
The diagnostic report says this:

Process:         gfxCardStatus [1015]
Path:            /Applications/gfxCardStatus.app/Contents/MacOS/gfxCardStatus
Identifier:      com.codykrieger.gfxCardStatus
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [309]
Responsible:     gfxCardStatus [1015]
User ID:         501

Date/Time:       2015-08-13 11:36:53.597 -0300
OS Version:      Mac OS X 10.9.5 (13F1096)
Report Version:  11
Anonymous UUID:  0C298ED6-81C2-E030-9E52-41BD60ABE63F

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/ReactiveCocoa.framework/ReactiveCocoa
  Referenced from: /Applications/gfxCardStatus.app/Contents/MacOS/gfxCardStatus
  Reason: no suitable image found.  Did find:
	/Applications/gfxCardStatus.app/Contents/MacOS/../Frameworks/ReactiveCocoa.framework/ReactiveCocoa: file too short
	/Applications/gfxCardStatus.app/Contents/MacOS/../Frameworks/ReactiveCocoa.framework/ReactiveCocoa: file too short

Binary Images:
    0x7fff62a97000 -     0x7fff62aca817  dyld (239.4) <7AD43B9B-5CEA-3C7E-9836-A06909F9CA56> /usr/lib/dyld
    0x7fff91733000 -     0x7fff918cfff3  com.apple.QuartzCore (1.8 - 332.4) <CFB972D1-FA37-380C-9A47-2A67A84B7442> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore

**Comment by codykrieger** [comment]
Unzip the archive with OS X's built-in Archive Utility instead of The Unarchiver or whatever other utility you used.
