### ISSUE TITLE
Switching

### ISSUE THREAD

**Issue by Khosrownia** [codykrieger/gfxCardStatus#210]
Hi,

On my MBP model 9,1 with integrated and discrete graphics controllers and latest Yosemite OS, and latest gfx, when I launch Photoshop Bridge CS5, gfx reports that the graphics has switched to discrete. When I close it, gfx reports a switch back to integrated. But when I launch Photoshop CS5 itself the switch from integrated to discrete doesn't take place. When I launch Nikon Capture NX-D the switch from integrated to discrete doesn't happen.

What is obvious is that Photoshop CS5 and Nikon Capture NX-D are not designed to take advantage of the discrete graphics controller which is more powerful than the integrated one. It is strange though.

What is not obvious is whether or not gfx is catching those two applications.

Is there a way I can manually activate the discrete controller?

Thanks

Farzad

**Comment by codykrieger** [comment]
Yeah—use Discrete Only mode.
