### ISSUE TITLE
Chosen monitor Color Sync Profile lost when switching to discrete

### ISSUE THREAD

**Issue by dpolzine** [codykrieger/gfxCardStatus#211]
MacBook Pro 15" early 2011; 16 GB RAM OS X 10.10.5

As a photographer I have calibrated my monitor and saved it as a custom profile. These color sync profiles are selected in the Color tab of the Displays System Preference. gfxCardStatus has always played nice with this until the latest release. Now when it switches from integrated to discrete the profile is ignored completely which in my case makes the display much bluer and brighter adversely affecting my ability to properly process my images.

**Comment by codykrieger** [comment]
gfxCardStatus can't do anything about this. Sorry.

**Comment by dpolzine** [comment]
Hmm, it didn't do this until the latest gfxCardStatus update, but your reply got me try some old school Mac voodoo, zapping the PRAM, and voila now when switching occurs the selected Color Sync Profile is no longer ignored.
