### ISSUE TITLE
gfxCardStatus can work on Windows7 thru bootcamp?

### ISSUE THREAD

**Issue by kanarko** [codykrieger/gfxCardStatus#212]
Hi I am trying to switch the GPU to intel Graphics while running Windows 7 on my MBP (15-inch, Mid 2010), but I don't know how. After a while working on windows (Autocad and Aspire softaware) my screen goes black and I need to restart. Does anyone found a solution to this. 
Much appreciate in advance for any help.

Cheers!

**Comment by codykrieger** [comment]
This is not possible.
