### ISSUE TITLE
15" MBP 10.6.8

### ISSUE THREAD

**Issue by dhork** [codykrieger/gfxCardStatus#213]
Hello! Sorry to file this as an issue, as it's really my issue. But I have an old 15" mid-2010 MBP with 10.6.8 installed, and I've started using more lately. But it has the graphics chip bug and crashes every now and then. I keep "Automatic Graphics Switching" disabled all the time in the Preference panel but every time it crashes it re-enables and I have to remember to go in on reboot and disable it. It was covered by a recall, but that's expired now.

I am hoping this app will let me force the graphics mode to be discrete all the time and make the bug go away. Even if it doesn't help, I'm hoping it will help me see the problem more clearly. I see that the latest version doesn't support 10.6.8 . Is there a prior version that I can try compiling that will work? I have the proper XCode installed but haven't used it in years. I can try compiling it if I knew which tag would work with 10.6.8. (I can't find this information in the release notes).

Thank you!

**Comment by codykrieger** [comment]
I think the last version to support 10.6 might have been v2.1? It's been so long now I can't remember.

https://github.com/codykrieger/gfxCardStatus/tree/v2.1

Give that a shot—but there are lots of bugs in versions older than v2.3, so YMMV.
