### ISSUE TITLE
help: how to upgrade OSX when gfxcardstatus is needed at startup?

### ISSUE THREAD

**Issue by sntrnr** [codykrieger/gfxCardStatus#214]
Dear Cody,

thank you for making gfxcardstatus. Without it I couldn't use my Macbook anymore because only the integrated Graphics card works.

I'm running OSX 10.7.5. and I wonder if there is any way I could upgrade to Yosemite or Maverick?
I'm scared that while upgrading or after upgrading gfxcardstatus is disabled or removed and I cannot reinstall it quickly enough. I often only have a few seconds after startup to switch manually before screen goes blank.

Does anyone know anything about this topic?
I would be very grateful for any information...

**Comment by codykrieger** [comment]
gfxCardStatus won't be disabled or removed if you upgrade OS X, but I can't say whether gfxCardStatus will launch fast enough to lock in the integrated GPU. Make a backup of your machine in its current state and try upgrading; you can always roll back if the upgrade proves too unstable.

**Comment by sntrnr** [comment]
Thank you for this quick reply. So nice of you.
Just because I'm a bit scared of all of this: Do you mean creating a bootable backup of some sorts?
Or is a normal backup sufficient? I'm just not sure if I can start the macbook to perform 'rolling back' when the broken Nvidia card may be needed during this process...

**Comment by codykrieger** [comment]
You could try a Time Machine backup, but a bootable backup would be safer (and take less time to restore). You can make a bootable backup with something like Carbon Copy Cloner.

**Comment by sntrnr** [comment]
Okay. I had a feeling that would be the answer.

Again: Thank you very much. Your tool is the most important one ever invented!
I wish you all the best!!
