### ISSUE TITLE
Mini DisplayPort adpators fail to start when in dynamic switching mode

### ISSUE THREAD

**Issue by MrRadiotron** [codykrieger/gfxCardStatus#217]
MacBook Pro Retina 11,3
I leave gfxCardStatus in dynamic switching mode, when plugging in either a Mini DisplayPort to VGA adapter or Mini DisplayPort to HDMI/DVI/DisplayPort combo adaptor, the integrated screen flashes black once, no video is output to external screen. Quitting gfxCardStatus allows the adpators to function.

**Comment by codykrieger** [comment]
Closing this very old bug—I'm not aware of any other reports of this, and if the machine is misbehaving while on Dynamic Switching mode (when macOS is controlling the GPU switching), then it's most likely a macOS bug.
