### ISSUE TITLE
10.10.5 compatibility?

### ISSUE THREAD

**Issue by anthonyeleven** [codykrieger/gfxCardStatus#218]
Over a year ago I began experiencing frequent lockups, apps on my early 2013 MBPR would progressively pinwheel, though curiously softphone audio was always the last to drop.  Had to power-cycle to recover.

It seemed consistent with https://www.apple.com/support/macbookpro-videoissues/ , but Apple claimed my SN was out of scope.

I found gfxCardStatus and forcing discrete graphics dramatically improved the situation. Until this week when it returned, shortly after I applied 10.10.5.

So, the question is whether something changed in 10.10.5 to prevent it from fully working, or if this is a co-incidence.

**Comment by codykrieger** [comment]
If all you want to do is force discrete graphics, turn off the `Automatic graphics switching` option in System Preferences > Energy Saver. You don't need gfxCardStatus for that.

**Comment by anthonyeleven** [comment]
I did that several days ago without effect.

**Comment by codykrieger** [comment]
Then there's nothing gfxCardStatus can do to help you—it effectively does the same thing as toggling that checkbox does. Something very well may have changed in 10.10.5 that is exacerbating the problems you were already seeing.

**Comment by anthonyeleven** [comment]
Thanks.  Had to ask, trying to avoid the nightmare of getting a nasty refurb from the company.

**Comment by codykrieger** [comment]
gfxCardStatus does some additional things to fool OS X into thinking that you're on an older model MacBook Pro that didn't have automatic switching, which is why you're seeing the Energy Saver prefpane differences. If you switch back to Dynamic Switching and quit gfxCardStatus the prefpane should return to normal.
