### ISSUE TITLE
"GfxCardStatus" is damaged and can't be opened.  You should move it to the Trash.

### ISSUE THREAD

**Issue by HectorDemon** [codykrieger/gfxCardStatus#219]
Good Afternoon,

     I am not a programmer.  However, I have a 2010 Macbook Pro that is having the Nvideo kernal crash issue.  I have been reading that your "GfxCardStatus" is my fix.  However, I can't seem to find a working version.  Can you please help me?

My Machine is:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro6,2
  Processor Name:	Intel Core i7
  Processor Speed:	2.66 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	8 GB
  Processor Interconnect Speed:	4.8 GT/s
  Boot ROM Version:	MBP61.0057.B0F

Thank You in advance!

Shane Rimer

**Comment by codykrieger** [comment]
Unzip the gfxCardStatus download with OS X's built in Archive Utility, not The Unarchiver or 7-Zip. Those programs don't properly extract the .zip file.

That said, you should not expect gfxCardStatus to be anything more than a half-baked workaround for your issue that only sometimes works. Better to get a new machine when you have the opportunity.
