### ISSUE TITLE
Chrome not starting unless I force "Discrete only" mode

### ISSUE THREAD

**Issue by alvarotrigo** [codykrieger/gfxCardStatus#221]
Chrome not starting unless I force "Discrete only" mode.

Also, randomly, while I'm using Chrome it changes from discrete only to Integrated only and this causes Chrome to crash and show a blank page in all its tabs forcing me to relaunch it. 

And I'm not quite sure about the relation with this other issue, but from time to time my Mac crashes and I have to restart it again. (although music still playing and so on).

I'm using Mac Os El Capitan. I have a MacBook Pro from mid 2012 If I remember it correctly.

**Comment by codykrieger** [comment]
Those are both Chrome issues; not sure there's any advice I can offer there.

As far as OS X crashing goes, it seems likely that you have faulty hardware, which could be exacerbating the issues with Chrome (or vice versa). Maybe take the machine to an Apple Store?
