### ISSUE TITLE
MacBook Pro random restarts when in Dynamic Switching or Discrete Onle

### ISSUE THREAD

**Issue by AngelInfinite** [codykrieger/gfxCardStatus#222]
I am getting constant kernel panics that I believe are due to the gfx card (Built-in Intel HD Graphics 288 MB, NVIDIA GeForce GT 330M PCle) I have on my mid-2010 MacBook Pro. I am running OS X 10.11.1 El Capitan. These crashes happened in El Capitan as well as in Mountain Lion. I manually make the computer to run in Integrated Only but if the computer falls asleep it will switch back to Dynamic and inevitably my computer crashes. Is there a way I can make it permanently in Integrated only (I don't know if this is bad or not...)? Or can I remove the PCle NVIDIA? I have troubleshot this problem in many ways but I think this is the problem. I pasted the latest panic report below, just in case you need it. Thank you... 

Anonymous UUID:       F2B4A072-D1FD-907E-A948-57CAC9B1E927

Wed Nov 25 07:40:06 2015

*** Panic Report ***
panic(cpu 0 caller 0xffffff7fa0045bad): "GPU Panic: [<None>] 5 3 7f 0 0 0 0 3 : NVRM[0/1:0:0]: Read Error 0x00000100: CFG 0xffffffff 0xffffffff 0xffffffff, BAR0 0xd2000000 0xffffff9138d8a000 0x0a5480a2, D0, P2/4\n"@/Library/Caches/com.apple.xbs/Sources/AppleGraphicsControl/AppleGraphicsControl-3.11.33.1/src/AppleMuxControl/kext/GPUPanic.cpp:127
Backtrace (CPU 0), Frame : Return Address
0xffffff914f022ed0 : 0xffffff801cee5307 
0xffffff914f022f50 : 0xffffff7fa0045bad 
0xffffff914f023030 : 0xffffff7f9dbe9fa4 
0xffffff914f0230f0 : 0xffffff7f9dcb6add 
0xffffff914f023130 : 0xffffff7f9dcb6b48 
0xffffff914f0231b0 : 0xffffff7f9df3ba23 
0xffffff914f023320 : 0xffffff7f9dcdab79 
0xffffff914f023340 : 0xffffff7f9dbf0cfd 
0xffffff914f0233f0 : 0xffffff7f9dbee690 
0xffffff914f0235f0 : 0xffffff7f9dbf0141 
0xffffff914f0236c0 : 0xffffff7f9f4cba47 
0xffffff914f023790 : 0xffffff7f9f4f61df 
0xffffff914f023820 : 0xffffff7f9f4de201 
0xffffff914f023880 : 0xffffff7f9f4deb22 
0xffffff914f0238d0 : 0xffffff7f9f4dee77 
0xffffff914f023940 : 0xffffff7f9f4df6f1 
0xffffff914f023980 : 0xffffff7f9f4ac4e0 
0xffffff914f023b00 : 0xffffff7f9f4ab03b 
0xffffff914f023b50 : 0xffffff801d4e3016 
0xffffff914f023b80 : 0xffffff801d4e48e0 
0xffffff914f023be0 : 0xffffff801d4e1967 
0xffffff914f023d20 : 0xffffff801cfa07d0 
0xffffff914f023e30 : 0xffffff801cee9aa3 
0xffffff914f023e60 : 0xffffff801cecd478 
0xffffff914f023ea0 : 0xffffff801cedcfd5 
0xffffff914f023f10 : 0xffffff801cfc13aa 
0xffffff914f023fb0 : 0xffffff801cff4b36 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleMuxControl(3.11.33b1)[FF6CE9C5-9D8F-3A48-9D10-2BB9C2DDD227]@0xffffff7fa0037000->0xffffff7fa004afff
            dependency: com.apple.driver.AppleGraphicsControl(3.11.33b1)[4ADB751E-5208-3DA7-A8C3-E9EC07263B16]@0xffffff7fa002f000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[CBAE26D8-0ACB-3C1F-8347-FDCA67EC40B3]@0xffffff7f9d9b4000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[8E5F549E-0055-3C0E-93F8-E872A048E31B]@0xffffff7f9d72d000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[48AC8EA9-BD3C-3FDC-908D-09850215AA32]@0xffffff7f9db3c000
            dependency: com.apple.driver.AppleBacklightExpert(1.1.0)[5CB7D4B7-B100-34EE-BD40-1EC07E865C67]@0xffffff7fa0032000
         com.apple.nvidia.classic.NVDAResmanTesla(10.0)[05FC5D7E-BB0B-3232-BBBD-8A49B6870D8B]@0xffffff7f9db93000->0xffffff7f9de08fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[8E5F549E-0055-3C0E-93F8-E872A048E31B]@0xffffff7f9d72d000
            dependency: com.apple.iokit.IONDRVSupport(2.4.1)[814A7F4B-03EF-384A-B205-9840F0594421]@0xffffff7f9db83000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[48AC8EA9-BD3C-3FDC-908D-09850215AA32]@0xffffff7f9db3c000
         com.apple.nvidia.classic.NVDANV50HalTesla(10.0)[56199CA6-3C8D-3EBB-B5EF-7B1B4678ACF9]@0xffffff7f9de13000->0xffffff7f9e0c0fff
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.0)[05FC5D7E-BB0B-3232-BBBD-8A49B6870D8B]@0xffffff7f9db93000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[8E5F549E-0055-3C0E-93F8-E872A048E31B]@0xffffff7f9d72d000
         com.apple.GeForceTesla(10.0)[49982DF3-8146-3BD0-AD3F-A7E7AB5ACBB5]@0xffffff7f9f499000->0xffffff7f9f564fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[8E5F549E-0055-3C0E-93F8-E872A048E31B]@0xffffff7f9d72d000
            dependency: com.apple.iokit.IONDRVSupport(2.4.1)[814A7F4B-03EF-384A-B205-9840F0594421]@0xffffff7f9db83000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[48AC8EA9-BD3C-3FDC-908D-09850215AA32]@0xffffff7f9db3c000
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.0)[05FC5D7E-BB0B-3232-BBBD-8A49B6870D8B]@0xffffff7f9db93000

BSD process name corresponding to current thread: WindowServer

Mac OS version:
15B42

Kernel version:
Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64
Kernel UUID: AB5FC1B4-12E7-311E-8E6F-9023985D8C1D
Kernel slide:     0x000000001cc00000
Kernel text base: 0xffffff801ce00000
__HIB  text base: 0xffffff801cd00000
System model name: MacBookPro6,2 (Mac-F22586C8)

System uptime in nanoseconds: 251590445774
last loaded kext at 64407918897: com.apple.driver.AudioAUUC	1.70 (addr 0xffffff7f9f78b000, size 32768)
loaded kexts:
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.driver.AppleTyMCEDriver	1.0.2d2
com.apple.driver.AGPM	110.20.21
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleHDAHardwareConfigDriver	272.50.31
com.apple.driver.pmtelemetry	1
com.apple.driver.AppleIntelHDGraphics	10.0.0
com.apple.driver.AppleHDA	272.50.31
com.apple.GeForceTesla	10.0.0
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleMikeyDriver	272.50.31
com.apple.iokit.IOBluetoothSerialManager	4.4.2f1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.AppleIntelHDGraphicsFB	10.0.0
com.apple.driver.AppleBacklight	170.8.1
com.apple.driver.AppleMCCSControl	1.2.13
com.apple.nvidia.NVDAStartup	10.0.6
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.4.2f1
com.apple.driver.AppleSMCLMU	208
com.apple.driver.AppleMuxControl	3.11.33b1
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.AppleLPC	3.1
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.driver.AppleUSBTCButtons	245.4
com.apple.iokit.IOBluetoothUSBDFU	4.4.2f1
com.apple.driver.AppleUSBTCKeyEventDriver	245.4
com.apple.driver.AppleUSBTCKeyboard	245.4
com.apple.driver.AppleUSBStorageCoexistentDriver	3.7.1
com.apple.driver.AppleUSBCardReader	3.7.1
com.apple.driver.AppleIRController	327.5
com.apple.driver.CoreStorageFsck	517
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	37
com.apple.iokit.SCSITaskUserClient	3.7.7
com.apple.iokit.IOAHCIBlockStorage	2.8.0
com.apple.driver.AppleFWOHCI	5.5.2
com.apple.driver.AirPort.Brcm4331	800.20.24
com.apple.driver.AirPort.Brcm4360	1010.14.1a4
com.apple.driver.AppleAHCIPort	3.1.5
com.apple.driver.usb.AppleUSBEHCIPCI	1.0.1
com.apple.iokit.AppleBCM5701Ethernet	10.1.11
com.apple.driver.usb.AppleUSBUHCIPCI	1.0.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	4.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	4.0
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	218.0.0
com.apple.nke.applicationfirewall	163
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	218.0.0
com.apple.AppleGraphicsDeviceControl	3.11.33b1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	272.50.31
com.apple.kext.OSvKernDSPLib	525
com.apple.nvidia.classic.NVDANV50HalTesla	10.0.0
com.apple.nvidia.classic.NVDAResmanTesla	10.0.0
com.apple.iokit.IOSurface	108.0.1
com.apple.iokit.IOSerialFamily	11
com.apple.driver.CoreCaptureResponder	1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleSMBusController	1.0.14d1
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.4.2f1
com.apple.iokit.IOBluetoothFamily	4.4.2f1
com.apple.iokit.IOFireWireIP	2.2.6
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleGraphicsControl	3.11.33b1
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.AppleHDAController	272.50.31
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.iokit.IOHDAFamily	272.50.31
com.apple.iokit.IOAudioFamily	204.1
com.apple.vecLib.kext	1.2.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d7
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.usb.IOUSBHostHIDDevice	1.0.1
com.apple.driver.AppleUSBMultitouch	250.4
com.apple.iokit.IOUSBMassStorageClass	4.0.0
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.7
com.apple.iokit.IOUSBMassStorageDriver	1.0.0
com.apple.iokit.IOUSBHIDDriver	900.4.1
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.0.1
com.apple.driver.CoreStorage	517
com.apple.driver.usb.AppleUSBHub	1.0.1
com.apple.iokit.IOSCSIMultimediaCommandsDevice	3.7.7
com.apple.iokit.IOBDStorageFamily	1.8
com.apple.iokit.IODVDStorageFamily	1.8
com.apple.iokit.IOCDStorageFamily	1.8
com.apple.driver.AppleXsanScheme	3
com.apple.iokit.IOAHCISerialATAPI	2.6.2
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.7
com.apple.driver.AppleUSBMergeNub	900.4.1
com.apple.iokit.IOFireWireFamily	4.5.8
com.apple.iokit.IO80211Family	1101.24
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IOAHCIFamily	2.8.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOEthernetAVBController	1.0.3b3
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.usb.AppleUSBUHCI	1.0.1
com.apple.driver.usb.AppleUSBEHCI	1.0.1
com.apple.iokit.IOUSBHostFamily	1.0.1
com.apple.driver.AppleUSBHostMergeProperties	1.0.1
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	415
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	4.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0

**Comment by codykrieger** [comment]
There's no way to make the machine stay in Integrated Only mode permanently. Sorry.

**Comment by AngelInfinite** [comment]
Ok, thanks. Do you think that that is a probable issue causing kernel
panics? I have seen a couple entries online about people with similar
issues thinking it is the gfx. I have a mid-2010 MacBook Pro so I know the
hardware might not be entirely compatible. Any wisdom is much
appreciated...

**Comment by AngelInfinite** [comment]
Also - I can't find the "dependencies" list on my utility menu. It is not
on the drop-down menu, nor under preferences. Where is it, please?

On Wed, Nov 25, 2015 at 11:07 AM, Angel Allen <allen.angel.gabriel@gmail.com

**Comment by codykrieger** [comment]
Yeah, graphics-related panics are common on 2010 models. I'd either take it to an Apple Store and have it looked at or just get a new machine.

The Dependencies list only shows up when the discrete GPU is in use.

**Comment by AngelInfinite** [comment]
Cool, thanks. Appreciate the quick responses. Happy Thanksgiving!

**Comment by baba-yaga** [comment]
Hi, Cody! I appreciate your very useful program, but I would like to join Angelinfinite's voice: I have also got this 2010 affected model and the Apple support for it is already ended :( I would prefer not to just throw it away, since, I know, it works great under integrated video mode. But as it was reported, it comes back to automatic after waking up or reboot and then inevitably crashes switching to discrete. Maybe there is a way to force switching to integrated? Maybe from a command line in .bashrc or similar? It would really save me (and any other people) a lot of money and frustration! Thank you again for your work!

**Comment by codykrieger** [comment]
Sorry, there's no way to do that.

**Comment by jaslegume** [comment]
Cody:

Your program was a godsend to me.  I have a 2010 macbook and when I was using Chrome the macbook would restart.  So I had to use Firefox.  Then I discovered your app and set it to integrated.  No more restarting.  Thank you so much
