### ISSUE TITLE
gfxCardStatus on the Mac App Store

### ISSUE THREAD

**Issue by outlyer** [codykrieger/gfxCardStatus#223]
This looks identical to gfxCardStatus but has a different name and author. Thought you might want to know. It doesn't even seem to have a different version number. 

https://itunes.apple.com/us/app/graphics-card-switcher-view/id1057013845?mt=12

![screen800x500](https://cloud.githubusercontent.com/assets/1550429/11532289/f1017e20-98d0-11e5-9e6c-f094f618d5b1.jpeg)

**Comment by codykrieger** [comment]
I'll be damned. Thanks for letting me know.

Aside from the fact that it's clearly a blatant ripoff, it doesn't belong on the Mac App Store due to its use of what is effectively private API (poking at undocumented behavior in the AppleGraphicsControl kernel extension).

**Comment by outlyer** [comment]
The fact that it's free makes me wonder if there are additional "features" (i.e. malicious ones) that the repackager has included. Either way, it's clearly not cool so I hope you're able to get it pulled.

**Comment by steveschow** [comment]
unfortunately its not free, which DEFINITELY makes me wonder.  But it does have at least one small improvement, the menu icon changes to "d" when discrete only mode is engaged.

**Comment by codykrieger** [comment]
The app is no longer available on the store.

**Comment by codykrieger** [comment]
Thanks to everyone that reported this!
