### ISSUE TITLE
Feature Request - Ability to force Integrated (even if it keeps dedicated card powered on)

### ISSUE THREAD

**Issue by Gatepc** [codykrieger/gfxCardStatus#224]
Hello there, I created this account on Git just to post in here. I wanted to thank you first Cody Krieger. I actually remember the very first version of this app being posted in a macrumors thread that I had started (I was the guy that figured out how to tell what GPU was active using system information tool during 2010). 

Anyway I know this is perhaps a special case (but there was a GPU recall so perhaps not!) but my dedicated GPU is completely shot. If my computer switches to it given about 30 secs to 5 mins it will kernel panic and this leads me to a major problem. Even if I have integrated mode selected it will switch to the dedicated GPU if I open certain apps (Such as Spotify) Now I believe that its possible to force it to stay on the integrated GPU at the expense of sending power to the unused dedicated GPU. I understand this will lower battery life and produce more heat, but to people in my situation this would be ideal rather then have a semi useless computer. Speaking as GPU recalls are not uncommon (especially in the macbook pro series) I think this would be a great feature even if you had to check a box specifically allowing it and excluding you from any potential damage etc. 

Thank you for your time, I'm not a programmer but I do have a degree in computer hardware. If there is anyway I can help or contribute let me know!

**Comment by mpena2099** [comment]
Same with me...

**Comment by codykrieger** [comment]
Unfortunately, gfxCardStatus is effectively on life support at this point. It's currently a little broken, and has been since OS X 10.8 came out. In the short term, I don't have plans to make changes to it beyond what's absolutely necessary, because I don't have the time to do so. Sorry. :/

**Comment by Gatepc** [comment]
> On Dec 30, 2015, at 11:02 AM, Cody Krieger <notifications@github.com> wrote:
> 
> Unfortunately, gfxCardStatus is effectively on life support at this point. It's currently a little broken, and has been since OS X 10.8 came out. In the short term, I don't have plans to make changes to it beyond what's absolutely necessary, because I don't have the time to do so. Sorry. :/
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/codykrieger/gfxCardStatus/issues/224#issuecomment-168024432>.
> 
Thats alright I understand how projects can get. If I was a programmer I’d donate time for this but unfortunately its never been my forte. Thank you none the less for your reply.
