### ISSUE TITLE
Sparkle vulnerability

### ISSUE THREAD

**Issue by kevin1** [codykrieger/gfxCardStatus#226]
Hi Cody,

gfxCardStatus doesn't load its updates over HTTPS, making it likely affected by the recent Sparkle vulnerability. Specifically, a MITM attacker can execute arbitrary remote code when the SUFeedURL isn’t loaded over HTTPS: 

http://gfx.io/appcast.xml

More information about the vulnerability: 

https://vulnsec.com/2016/osx-apps-vulnerabilities/
https://www.evilsocket.net/2016/01/30/osx-mass-pwning-using-bettercap-and-the-sparkle-updater-vulnerability/

Thanks! Hope to see it updated soon,
Kevin

**Comment by codykrieger** [comment]
Fixed in #225. I'll leave this open until a new version has been released with the fix.

**Comment by zachriggle** [comment]
All users are still vulnerable to this, since the latest version is still v2.3.

Would you mind cutting a new release, which either:

1. Disables Sparkle update entirely
2. Uses the fix from #225 

Thanks!

**Comment by mgol** [comment]
This seems to be a big vulnerability which may lead to arbitrary code execution... :/ Could we get a release?

**Comment by mgol** [comment]
Ping @codykrieger, could we have a release?

**Comment by codykrieger** [comment]
Finally (!) putting out a beta release that fixes this and includes some Big Sur fixes (#336).

**Comment by codykrieger** [comment]
Alright—fixed in v2.5b1: https://gfx.io/downloads/gfxCardStatus-2.5b1.zip
