### ISSUE TITLE
External Graphic Card support request..

### ISSUE THREAD

**Issue by chayneps** [codykrieger/gfxCardStatus#227]
Now, there's many products offer extend graphic card via Thunderbolt port, such as BizonBox(https://bizon-tech.com/us/bizonbox2-egpu.html). For me as a java developer, I use external graphic card for connecting to external monitors in order to decrease heat producing by Macbook Pro, itself. It works really well especially, if you need to connect 2 4K monitors.

I normally use gfxCardStatus to decrease the heat by use "Integrated only" option. However, gfxCardStatus always assume that "External Display" always connect with internal Discrete card. Therefore, I cannot use "Integrated Only".

**Comment by codykrieger** [comment]
This is a hardware limitation, sorry.

**Comment by codykrieger** [comment]
@JMY1000 The macOS version is irrelevant. The graphics muxing hardware on the MacBook Pro logic board can only switch between the onboard discrete and integrated GPUs.

**Comment by JMY1000** [comment]
Understood, I more just wanted to see if it'd be possible to get it to recognize when an eGPU is connected and display as such.
