### ISSUE TITLE
Help building in xcode

### ISSUE THREAD

**Issue by steveschow** [codykrieger/gfxCardStatus#228]
Can anyone provide some insights for how to get this to build in Xcode, for an Xcode newbie.  Looks like some stuff related to ReactiveCocoa needs to be present, but I'm not sure what it is I need to obtain to satisfy that.  I'm new to Xcode but not new to programming.

**Comment by codykrieger** [comment]
GitHub issues aren't really meant to act as a support forum; they're meant to report bugs with the project. That being the case, closing.
