### ISSUE TITLE
GFX Card Status is showing false information on MacBook Pro 15 2015 with M370X

### ISSUE THREAD

**Issue by tdavydov** [codykrieger/gfxCardStatus#236]
You should run temperature monitor for the dedicated GPU, since its the only way to really tell when the dedicated cards kicks in. 

Best way to activate it is to swipe between multiple desktops back and forward. This will immediately switch to M370X, and the temperature will just from 35 degrees celsius to low-mid 50's.

However! GFX Card status will still show Iris Pro running. Its not as much of a programs's fault, but a bug with MacBook, since iStat is showing the same exact behavior. 

Once it switches to the dedicated card, it will not go back to Iris Pro unless you manually switch to Dedicated, and then back to Integrated.  Temperature drops to 35 degrees immediately.

**Comment by codykrieger** [comment]
I haven't been able to reproduce this. That said, temperature is not an accurate indicator of which GPU is on—so many other things could have happened when you swiped between desktops to cause the temperature inside the machine to rise.
