### ISSUE TITLE
mbfloagent dependency wont let me switch to integrated even though im on integrated?

### ISSUE THREAD

**Issue by kylecannon** [codykrieger/gfxCardStatus#238]
Running 10.11.5 OSX

<img width="228" alt="screenshot 2016-05-25 07 43 38" src="https://cloud.githubusercontent.com/assets/867978/15544118/75aca852-224c-11e6-9635-a58935922154.png">

<img width="434" alt="screenshot 2016-05-25 07 43 44" src="https://cloud.githubusercontent.com/assets/867978/15544126/7caaddae-224c-11e6-94e5-5e8d4d79ff7a.png">

**Comment by codykrieger** [comment]
This isn't a bug. I don't know what mbfloatagent is, but it's causing your discrete GPU to turn on. You have to quit it before gfxCardStatus will allow you to switch GPUs.

**Comment by nikoloza** [comment]
It comes from `Photos.app`, you should just disable it from [startup processes](http://www.macworld.com/article/2047747/take-control-of-startup-and-login-items.html)

**Comment by JayBrown** [comment]
In my case I've only noticed that mbfloagent always runs after login following macOS system upgrades or updates. (Noticed this when moving from El Capitan to High Sierra.) The process will exit after 30 to 60 seconds, but until then you have to pray that there's no GPU panic. :)
