### ISSUE TITLE
Preserve settings after boot

### ISSUE THREAD

**Issue by astrofrog** [codykrieger/gfxCardStatus#239]
I am using gfxcardstatus because my macbook pro keeps crashing with GPU panic when using the NVIDIA card. Using the 'integrated only' mode helps me avoid these crashes. However, every time I restart the computer, gfxcardstatus reverts back to 'dynamic switching'

Would it be possible to add an option to preserve settings across reboots?

**Comment by codykrieger** [comment]
Unfortunately, no. A similar feature caused far too many headaches in the past, so I'll not be adding it back.
