### ISSUE TITLE
Uninstalled gfxCardStatus and external monitor does not work anymore

### ISSUE THREAD

**Issue by felipedrumond** [codykrieger/gfxCardStatus#241]
I just installed gfxCardStatus and uninstalled it since to use an external monitor needs the discrete graphics card. Now the El Capitan detects the external monitor, but does not show any image.

**Comment by codykrieger** [comment]
Try resetting your PRAM? gfxCardStatus doesn't leave any state behind that would cause this kind of issue. More likely OS X's or your hardware's fault.

**Comment by felipedrumond** [comment]
Hi codykrieger, I had to unplug the external monitor from MBP and restart. Strange but that solved the problem.

**Comment by codykrieger** [comment]
Glad to hear it! External display support on OS X has always been...flaky at best.
