### ISSUE TITLE
3D apps broken after turning on Integrated mode

### ISSUE THREAD

**Issue by antonshiryaev** [codykrieger/gfxCardStatus#247]
3D apps either don't launch at all, or launch with odd positioning and really low framerates. 2015 15" rMBP. Is there a log I need to submit?

**Comment by codykrieger** [comment]
macOS version? gfxCardStatus version? Apps you're running?

**Comment by antonshiryaev** [comment]
OS X 10.11.5, gfxCardStatus 2.3. 

Strangely, I wasn't able to reproduce it this morning. I'll write back once I can.
