### ISSUE TITLE
''unsupported machine'' message after restart 

### ISSUE THREAD

**Issue by Siegbert774** [codykrieger/gfxCardStatus#248]
It says ''UnupportedMachine'' all of a sudden 
I really need it to work cause otherwise my macbook will crash with every automatic card switch 
pls help! 

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro6,2
      Processor Name: Intel Core i5
      Processor Speed: 2,4 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 3 MB
      Memory: 8 GB
      Processor Interconnect Speed: 4,8 GT/s
      Boot ROM Version: MBP61.0057.B11
      SMC Version (system): 1.58f17
      Sudden Motion Sensor:
          State: Enabled

Graphics/Displays:

    NVIDIA GeForce GT 330M:

      Chipset Model: NVIDIA GeForce GT 330M
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x16
      VRAM (Total): 256 MB
      Vendor: NVIDIA (0x10de)
      Device ID: 0x0a29
      Revision ID: 0x00a2
      ROM Revision: 3560
      Displays:
        Color LCD:
          Display Type: LCD
          Resolution: 1440 x 900
          Pixel Depth: 32-Bit Color (ARGB8888)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Built-In: Yes

**Comment by Siegbert774** [comment]
It seems as if the Intel HD Graphics Card disappeared. Does that mean it crashed?

**Comment by codykrieger** [comment]
I've seen this issue clear up for other people with an SMC reset. Not a gfxCardStatus bug, though.
