### ISSUE TITLE
Nvidia not showing on status

### ISSUE THREAD

**Issue by dcbgu255** [codykrieger/gfxCardStatus#250]
Hello my latest problem is Nvidia is not showing on the GFX card status app on my Macbook Pro 10.11.6 even though it is plugged in and showing on the Nvidia Manager.

Any ideas to what's keeping it from showing on the status.

**Comment by dcbgu255** [comment]
A bit of good news I decided to downgrade from 2.3 version to 1.8.1 and it is recognising Nvidia now so the only problem is version 2.3 not allowing to recognise Nvidia devices.

**Comment by codykrieger** [comment]
@dcbgu255 That's definitely not related to what gfxCardStatus version you have. People do occasionally see issues like this that require resetting your MacBook Pro's SMC: https://support.apple.com/en-us/HT201295

**Comment by dcbgu255** [comment]
Then why did it work after I downloaded a older version I do have the proof for this and I have reseted my macbook pro and that did not solve the GFXCardStatus of the Nvidia as it didn't have the option to switch GPU's except on the older version.

**Comment by dcbgu255** [comment]
Here is the time and screenshot proof of the version not working as I've just downloaded the latest version again and it still doesn't work but only when I downgrade.

![image](https://cloud.githubusercontent.com/assets/22275277/18631309/27d68d4a-7e69-11e6-9289-f253c371db45.png)



![image](https://cloud.githubusercontent.com/assets/22275277/18631333/400a5522-7e69-11e6-961a-bb51ba495b59.png)
