### ISSUE TITLE
Nvidia not showing still on version 2.3

### ISSUE THREAD

**Issue by dcbgu255** [codykrieger/gfxCardStatus#251]
Hello again going back to what you previously said on the other topic of this I do have proof of it being the version not working which is on these screenshots as follows below as I've just downloaded the latest version again and it still doesn't recognise it but only when I downgrade.
The time is also on the screenshots of my desktop which explains it's not working I did restart my mac when I had the latest version and that did not solve it it also doesn't have swithing GPU's available.

What else could be causing the issue.

![image](https://cloud.githubusercontent.com/assets/22275277/18631699/65f6e8a2-7e6b-11e6-9782-b67fdff752bf.png)

![image](https://cloud.githubusercontent.com/assets/22275277/18631702/73969174-7e6b-11e6-9ffa-cc1726268e54.png)

**Comment by codykrieger** [comment]
Looks like it's working fine in v2.3—the problem appears to be that you don't know how to use gfxCardStatus. See https://gfx.io/switching.html.
