### ISSUE TITLE
Nvidia not showing still on version 2.3

### ISSUE THREAD

**Issue by dcbgu255** [codykrieger/gfxCardStatus#252]
Hello again as you said the main program is working fine but why isn't Nvidia showing on the status as it's just saying GPU AMD Radeon on the 2nd picture I gave you but on the first picture it has Nvidia Geforce 9600M.

Could you please tell me in detail what I'm missing otherwise I'll swap to a better graphics status program the link you gave doesn't explain the full issue unless they took away the switching GPU's?

So why is the Status different compared to my other photo what's different or causing it.

**Comment by codykrieger** [comment]
I really think this is all just an enormous misunderstanding, and you don't understand how to use gfxCardStatus. The link I gave you in the last issue you filed should explain everything.

However, if you insist that something is wrong, please run this command in Terminal and paste the output here: `system_profiler SPDisplaysDataType`.

**Comment by dcbgu255** [comment]
I know I just don't understand why the status of the graphics card is not listed of the Nvidia one instead of the other one?

**Comment by codykrieger** [comment]
I won't be able to figure that out without the output from the command that I asked for (`system_profiler SPDisplaysDataType`).

**Comment by dcbgu255** [comment]
Okay I'll paste it now.

**Comment by dcbgu255** [comment]
I'm gonna restart my mac with the device attached and paste it in terminal.

**Comment by codykrieger** [comment]
With what device attached?

**Comment by dcbgu255** [comment]
A Bizon box of Zotac Geforce GTX 970 as recognised as Nvidia Geforce 9600m.

**Comment by codykrieger** [comment]
Oh, well now everything makes sense. gfxCardStatus does not (and cannot) support external GPUs.

**Comment by dcbgu255** [comment]
Oh I see well thanks for the help you've done by mentioning the terminal paste.

I'll see if any other program supports external graphics cards.
