### ISSUE TITLE
Magic move in Keynote has problem with integrated-only mode.

### ISSUE THREAD

**Issue by weihsuanchen** [codykrieger/gfxCardStatus#255]
Hello guys,
My Laptop is MacBook Pro 15 2010-mid with Sierra and Keynote 7.0.5(the latest version),
and I use the gfxCardStatus 1.8.1 with integrated-only mode,
when I use the magic move in Keynote, the screen will be black,
I have try downgrade the Keynote version to 6.6.2,
but the problem still exist.

Anyone who with the same environment to me,
has the same problem?

Thanks guys.

**Comment by codykrieger** [comment]
@weihsuanchen That's basically expected behavior—some applications don't work properly when you force integrated graphics, particularly on 2010 machines.

**Comment by codykrieger** [comment]
(Note that this is not a gfxCardStatus issue—this is an issue with macOS, certain MacBook Pro models, and specific applications. There's no real way to fix this aside from “don't use Integrated Only mode.”)
