### ISSUE TITLE
gfxCardStatus depends on discrete GPU, prevents switching

### ISSUE THREAD

**Issue by chrisjcameron** [codykrieger/gfxCardStatus#256]
This is after a fresh restart. I am not sure it this started with Sierra but I have noticed much worse battery life since updating. 

![gfx_dependency](https://cloud.githubusercontent.com/assets/1383080/20975006/10abdc56-bc6c-11e6-86f8-3582e597af2f.png)

**Comment by codykrieger** [comment]
Dupe of #240.
