### ISSUE TITLE
Please transfer this project to new maintainers to avoid letting it die

### ISSUE THREAD

**Issue by jimbojetlag** [codykrieger/gfxCardStatus#257]
I'd like to thank the original author for building this software. I've been running it for years to protect a flaw that well deserves a lawsuit against Apple.

Unfortunately, gfxCardStatus has stopped working since Sierra #240. At the time of writing, the last commit of this project belongs to 8 months ago. In case the author is not going to maintain this project anymore, perhaps they should transfer it to other maintainers. Some have forked this project, which would lead to losing the focus of community. It would be best to keep the focus on a single project.

**Comment by malhal** [comment]
For anyone looking for that Sierra fork:

https://github.com/steveschow/gfxCardStatus/releases

**Comment by codykrieger** [comment]
@jimbojetlag I'd be more than happy to have a competent, trustworthy maintainer take over day-to-day operations. Thus far, I've not found one that fits that description.

**Comment by sporkman** [comment]
@codykrieger - I understand your concern, but the Sierra issue has been unfixed in the official repo for more than six months, and the fork may or may not have issues, but it does function.  I understand you are busy, but this project will come to an end at some point (once all the old hardware dies).  Perhaps encourage people to donate some money so you're compensated for your time?

In my case, the fork is allowing me to keep using a MBP that would likely fry its discrete graphics card if left to its own devices...  My point being, for some this is probably really critical software - what can those of us that need it do to encourage further development?

**Comment by niklaskorz** [comment]
To be fair, we do not need Cody's ok for starting a community-maintained fork. We already have all necessary tools at our hand thanks to Github. Now we just need folks who are willing to work on it.

**Comment by rafaelsales** [comment]
@codykrieger have you considered having a paid version like [Turbo Booster Switcher](http://www.rugarciap.com/turbo-boost-switcher-for-os-x/)? Or even having the free working for 30 days? That's more than enough o prove how useful is the app.

I would buy it now if it helped improving and keeping the app up to date.

**Comment by doctorpangloss** [comment]
I can go ahead and run the next fork, if you'd like, and get the signing / deployment infrastructure up and running (right now the most helpful fork isn't signed). I've been rescuing other handy Mac projects too, give me some time to catch up. It's great software @codykrieger !

**Comment by codykrieger** [comment]
It's only taken me 8 years, but I'm more-or-less actively maintaining this again. Closing.
