### ISSUE TITLE
Can'tSwitchToIntegratedOnlyPlural

### ISSUE THREAD

**Issue by Milanw2** [codykrieger/gfxCardStatus#259]
I'm getting an error on my Macbook Pro 15-inch mid 2010 with video cards NVIDIA GeForce GT
330M 512 MB & Intel HD Graphics 288 MB.
This is the error message:
Can'tSwitchToIntegratedOnlyPlural
gfxCardStatus
Google Chrome Helper
Google Chrome

Thanks in advance!

**Comment by codykrieger** [comment]
You're seeing two separate issues: #99 and #240.
