### ISSUE TITLE
"You are using a system that gfxCardStatus does not support"

### ISSUE THREAD

**Issue by ZiyaoM** [codykrieger/gfxCardStatus#263]
Hi all, 

I use MacOS Sierra 10.12.2 and just bought an external GPU to play games on my MacBook Pro (late 2016, 13in). I found "automatic switching graphics" option no longer available in "Energy Saver" panel so I tried gfxCardStatus. But it won't start and says that my system is not supported. What should I do?

**Comment by codykrieger** [comment]
Sorry, gfxCardStatus can't support external GPUs.
