### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by brooksbp** [codykrieger/gfxCardStatus#27]
How do you uninstall?  Why is there no support for uninstall?

**Comment by Drakas** [comment]
Why that file usually don't stay into the same directory? Are for a reinstall purpose?

**Comment by jboria** [comment]
I recommend using this free app, https://freemacsoft.net/appcleaner/ it completely removes everything. It has helped me many times!

**Comment by jboria** [comment]
> How do you uninstall? Why is there no support for uninstall?

I recommend using this free app, https://freemacsoft.net/appcleaner/ it completely removes everything. I tried it when uninstalling adobe cloud. It removed everything that their uninstall software left behind. You drag the app form the application folder and drop it right into the app cleaner and shows you all the files its removing.
