### ISSUE TITLE
Novice Needs Help For Late 2011 17" MBP & GFXCardStatus...

### ISSUE THREAD

**Issue by Baz777** [codykrieger/gfxCardStatus#271]
Hi All,

I am a novice with no experience in coding or anything like that. I have a Late 2011 17" 2.4 Macbook Pro running Mavericks.

A couple of weeks ago, I suffered a graphics issue 7 was lucky in that the MBP restarted & *seems* to be working OK - for the most part but I do still have some bugs & lock ups etc.

I was strongly told to install GFXCardStatus & leave it in Integrated Mode only. I have also set it so it automatically  logs in at start up & shows up in the menubar.

I saw a video on YouTube whereby one user stated that the latest version of GFX does not work for the Graphics issue on 2011 MBP's & to only use the previous 2.0.1 version which I was lucky enough to find & install.

Unfortunately, it is very buggy & I often have to quit it via Activity Monitor as many times, it shows as "Not Responding". When it does activate, it never defaults to the "Integrated" setting options inputed & shows a "D" in the menubar - however, when one checks the preferences, it will show that "Integrated Only" switched by itself to "Dynamic or Discrete Switching" even though under preferences, "Integrated" is selected on both Battery & Plugged In section. If I try to switch back to Integrated again, the app can hang & I ahem to force quit it & start all over again hoping that it will not hang again at start up.

If I manually make sure Integrated is set on all sections, it somehow sets itself to Discrete at a later stage & the only way one knows this us by checking as the "i" always shows in the menubar - so one always assumes that Integrated mode is in play when that may not be the case.

I would really appreciate some help & advice on resolving this matter & how to stop this issues happening as well as ensuring the App keeps everything in Integrated mode so my NBP is protected from the Graphics issue striking again - please see pics attached.

Many Thanks!

![screen shot 2017-03-15 at 19 01 32](https://cloud.githubusercontent.com/assets/26442768/23966054/ea4e5f8c-09b1-11e7-93c1-e421910551b3.png)

![screen shot 2017-03-15 at 15 18 56](https://cloud.githubusercontent.com/assets/26442768/23966068/f6520590-09b1-11e7-9c49-a86880833c3c.png)

![screen shot 2017-03-15 at 20 44 37](https://cloud.githubusercontent.com/assets/26442768/23970262/231e5d76-09c1-11e7-8b49-398d2890c716.png)

![screen shot 2017-03-15 at 15 18 36](https://cloud.githubusercontent.com/assets/26442768/23966294/b0d4d0b4-09b2-11e7-82b6-164d4302d1b5.png)

**Comment by steveschow** [comment]
try this one: https://github.com/steveschow/gfxCardStatus/releases/tag/v2.4.3i
