### ISSUE TITLE
MBP mid 2010 is crazy

### ISSUE THREAD

**Issue by nerohi** [codykrieger/gfxCardStatus#273]
Hi there!
Your little plug thingy saved my year. Those kernel panics have ruined my work and patience.. 
Since I started using the Integrated option the problem went away. 
Unfortunately, this week my computer went back into restarting itself multiple times a day. I am still running El Capitan (saw that some people here had problems with Sierra).
Do you perhaps know what went wrong? card switching is my only hope.

**Comment by nerohi** [comment]
Ok now it seems it switches to Discrete on its own which is why the kernel panics are happening again..

**Comment by steveschow** [comment]
try this: https://github.com/steveschow/gfxCardStatus/releases/tag/v2.4.3i

**Comment by nerohi** [comment]
Thanks, I'm trying it now. It appears to me that the computer stopped going to sleep now - perhaps this has some deal with Caffeine app I sometimes use?

**Comment by nerohi** [comment]
Another update - It does go to sleep, but weirdly lights up immediately when I open the cover, that's why I thought it never went to sleep. Also, if I leave Chrome on and walk away for even 10 minutes or any amount of tabs, the app doesn't respond anymore and I have to force quit. Every time I come back to the computer.
