### ISSUE TITLE
Can't switch to integrated at all

### ISSUE THREAD

**Issue by sitealacarte** [codykrieger/gfxCardStatus#274]
Every attempt tells me that "gfxCardStatusr" is running, and it wont switch. 

My actual issue is that I forgot and updated the software, when I was told I needed an older version that toggled between Intel and Nvidia. I have an older MacBook Pro with that video card issue, and when I force it to stay on Intel it works fine. 

Which of the posted versions will do what I need?

Thanks

**Comment by steveschow** [comment]
try this: https://github.com/steveschow/gfxCardStatus/releases

**Comment by sitealacarte** [comment]
Thanks Steve.
 I'm clear now that what I need to fix my specific problem is the compiled version of the 1.8.1 release of gfx. I'm currently running it in Xcode because the Build isn't creating an executable in the origin folder. I'm not sure what to do but keep it running in Xcode at this point. Any ideas?

**Comment by steveschow** [comment]
if you check the past discussions you will see that the older versions of gfxCardStatus have some serious bugs including it is not always integrated mode even when it says it is.  try the one I pointed you to it will solve your problem.

**Comment by sitealacarte** [comment]
Got it. Thanks Steve. It's working, pending I load Opera after I load the SW. But it's going. So leaving it on integrated will force the use of the Intel card instead of Nvidia?

**Comment by steveschow** [comment]
yes

**Comment by sitealacarte** [comment]
Thank you!
