### ISSUE TITLE
early 2011

### ISSUE THREAD

**Issue by mykin** [codykrieger/gfxCardStatus#276]
I have Macbook Pro 15inch early 2011:
https://support.apple.com/kb/sp620?locale=en_US
(with "Intel HD Graphics 30005" and "AMD Radeon HD 6750M" with automatic graphics switching)

My computer used to crush and showed blue screen when I used Adobe Premier Pro or Facebook Messenger(or some other websites) on Firefox/Opera/Safari (It went like this even if I disabled hardware acceleration. It works on Chrome, though).
Then I started using gfxCardstatus v2.3 and thus I could avoid the crush and blue screen. I could use Firefox peacefully if I turn on "Integrated Only" mode.

After a while, it started crushing again as soon as I turned on "Integrated Only" mode, so I don't turn it on anymore. 

Is it because both graphic cards went broken?
Or is there any other version of gfxCardstatus which would work better?

**Comment by codykrieger** [comment]
If your machine is _that_ broken, I'm not sure any version of gfxCardStatus can help you. Sorry.

**Comment by steveschow** [comment]
mykin try this: https://github.com/steveschow/gfxCardStatus/releases/tag/v2.4.3i

**Comment by mykin** [comment]
Thank you steveschow, I tried, but the same problem happened. I know this model of Macbook pro has an issue with "AMD Radeon HD 6750M", but now the other graphic card also might have broken.
