### ISSUE TITLE
Is it possible to use this on Mac like Hackintosh desktop?

### ISSUE THREAD

**Issue by luceat-lux-vestra** [codykrieger/gfxCardStatus#278]
I have HD4000 iGPU and discrete Radeon 7870.

I want to know it is possible to support systems like mine.
If can't, I want to know a reason especially it's restricted by hardware or software side.
I mean, If It's not restricted by some hardware that only exists on MBP, I guess it's possible to support Hackintosh.

How do you think?

Thanks.

**Comment by luceat-lux-vestra** [comment]
I think it's not possible on Hackintosh.

I found this.

https://www.tonymacx86.com/threads/dynamic-switch-igpu-and-dedicated-gpu-on-desktop.111900/

**Comment by codykrieger** [comment]
Nope, sorry.
