### ISSUE TITLE
Download link for the version that fixed the automatic switch.

### ISSUE THREAD

**Issue by sleepingpie** [codykrieger/gfxCardStatus#280]
https://gyazo.com/6e3b02ccd6d657c36641bdde6a67e57f

In the screenshot above someone posted a version of this software that blocks the switching from NVIDIA to INTEL completely, but the link doesn’t work anymore. The reason I need this is because my discrete GPU died, and every time an app attempts to access it, it shuts down the computer.

Even with gfxCardStatus 1.8.1 it still switches sometimes, so I need something to completely block the discrete card.

**Comment by codykrieger** [comment]
Hi @sleepingpie—if your discrete GPU has died (i.e. the NVIDIA GPU), then you'd want to use the integrated (i.e. Intel) one…you wouldn't want to prevent switching _to_ the integrated one as you suggest. Unfortunately, that is not possible.
