### ISSUE TITLE
Using External Display

### ISSUE THREAD

**Issue by eduardo4jesus** [codykrieger/gfxCardStatus#283]
I tried to force my computer to use `Integrated Only`, but as soon as I plug an external display using a thunder bold adapter, the `Dynamic Switching` mode is activated. Does this happen just with me? I external displays actually requires using the `Discrete GPU` (NVIDIA GeForce GT 330M 512 MB).

**Comment by codykrieger** [comment]
Yes, using an external display requires the discrete GPU.

**Comment by wagle** [comment]
I seem to now (past 2 years) require an external display to boot.
