### ISSUE TITLE
You can't switch to Integrated Only while the following items are running- gfxCardStatus

### ISSUE THREAD

**Issue by rronbajri** [codykrieger/gfxCardStatus#284]
@codykrieger I just updated my system to Sierra and discovered that I have a problem with gfxCardStatus. The warning is telling me to close gfxCardStatus in order to Switch to Integrated. Did anyone else had this problem? I can send you a screenshot if you need one.

-You can't switch to Integrated Only while the following items are running-
gfxCardStatus

**Comment by codykrieger** [comment]
Sounds like #162.
