### ISSUE TITLE
Where does gfxCardStatus take its icons from?

### ISSUE THREAD

**Issue by maciboy** [codykrieger/gfxCardStatus#285]
Hi!
I updated to 2.4.4…
Because of visual reasons I dislike the „I“ or „n“ symbol in the menu bar and regularly replace these images with Intel- and Nvidia images.
In the apps Contents/Ressources-folder there are png files stored.
I replaced them with my images using the exact names of the original icons.

However, gfxCardStatus after a restart still shows the old symbols instead of my images!?
Are there further changes needed so that gfxCardStatus shows my images?

These are my images: https://www.dropbox.com/sh/oea2mbd0z7rchzb/AACkAT3vBcKjxcTK4IniseQKa?dl=0

Thanks in advance for any hints!

**Comment by codykrieger** [comment]
The icons that gfxCardStatus draws in the menu bar these days are text, not images. Dropping images into the app bundle is no longer officially-supported.
