### ISSUE TITLE
Google Chrome launches on startup, discrete GPU is used.

### ISSUE THREAD

**Issue by larsloveslegos** [codykrieger/gfxCardStatus#286]
For some unknown reason, Google Chrome feels the need to start up even if it's not set to which causes it to use the discrete graphics. I'm using the mid 2010 MacBook Pro 15" which means the discrete GPU is death unless the issue is fixed on the logic board. As it starts up, I must quickly quit the application from the force quit menu. Otherwise, the MacBook will crash and I have to try again. Could a feature be added to where the program is able to start with the graphics of your choice and to forcibly quit any and all applications preventing it from switching? I love the application and what it does, it allows me to use my MacBook until I can get the logic board fixed. Thanks for any and all help!

**Comment by codykrieger** [comment]
Thanks for the report. We're tracking adding a feature like that back to gfxCardStatus in #150.
