### ISSUE TITLE
External Monitor Required on MBP 2010?

### ISSUE THREAD

**Issue by wagle** [codykrieger/gfxCardStatus#287]
As far as I can tell, I MUST have a monitor plugged into my MBP 2010 for it to be stable (and even then it takes several tries to reboot, each involving a ritual where I unplug the external monitor, power cycle it, and plug it back in).

But now I have a new MBP 2017, and I'd like to put the old MBP 2010 "out to pasture", and would like to keep it running in an out of the way spot, as a file server or something.

Anyone have any suggestions on how to keep the old MBP 2010 running without an external monitor?  gfxCardStatus under Sierra (and possibly a future High Sierra) didn't work a few weeks ago when I tried it.

**Comment by codykrieger** [comment]
I'd suggest quitting and removing gfxCardStatus, and then disable automatic graphics switching in System Preferences > Energy Saver. That may obviate the need for an external display to be plugged in at boot.

**Comment by wagle** [comment]
Tried this again.  It booted (!), but froze-with-pixels-missing after 5 minutes.

Just thought I’d ask.  Thanks!

— Perry

**Comment by elbotho** [comment]
@wagle this is probably too late for you, but there are several options to disable or even fix the discrete card. 
Here are some ideas:
https://github.com/steveschow/gfxCardStatus/issues/21

**Comment by wagle** [comment]
I did try some convoluted thing involving arch linux, but it didn't work.

I forecast a 50% chance I will go all packrat and try this, thanks!
