### ISSUE TITLE
feature request: make notifications optional

### ISSUE THREAD

**Issue by morandd** [codykrieger/gfxCardStatus#291]
Would be great to hvae a checkbox in Preferences so that we can choose whether notifications pop up all the time. For me, the status icon is enough; I don't need an OSX notification popup every time I switch tabs in chrome between a GPU/non-GPU page.

thanks for the great app!

**Comment by codykrieger** [comment]
You can disable notifications from gfxCardStatus in System Preferences > Notifications > gfxCardStatus by selecting “None” as the alert style.
