### ISSUE TITLE
gfxcardstatus 2.3

### ISSUE THREAD

**Issue by djgslimm** [codykrieger/gfxCardStatus#294]
Is there a way to make the gfxcardstatus app stay on one setting?.....I selected i and it keeps switching to n automatically...I just updated my IOS to high sierra due to the gfxcard status 2.1 stop working and the dreaded graphic card crashing started happening a week ago so I decided to update the operating system as well as the gfxstatus from 2.1 to 2.3 to see if my computer will stop re-setting itself...so far since i have done this no re-sets as of yet...I am just concern of why the gfxcardstatus keep switching modes ...while on the subject which is a better mode to keep my 2010 MacBook on while using the gfxcardstatus to ensure I will not be experiencing anymore re-sets?

**Comment by codykrieger** [comment]
Dupe of #103.
