### ISSUE TITLE
Graphics card switches despite OS settings (or notices are wrong)

### ISSUE THREAD

**Issue by anonymouscoward21** [codykrieger/gfxCardStatus#295]
MBP Retina, Late 2013 (MacBookPro11,3)
MacOS 10.13.1

My machine is set in Energy settings to disable automatic graphics switching, yet gfxCardStatus frequently reports switching to integrated graphics or being in Dynamic Switching mode.

**Comment by codykrieger** [comment]
gfxCardStatus overrides that setting in System Preferences > Energy Saver. If you want to truly disable automatic graphics switching, quit and remove gfxCardStatus, and *then* uncheck that checkbox.
