### ISSUE TITLE
Race condition after disconnecting power

### ISSUE THREAD

**Issue by gnachman** [codykrieger/gfxCardStatus#298]
iTerm2 will soon launch a feature where it uses the discrete GPU but only while power is connected. A user noticed that gfxCardStatus will notify the user that iTerm2 "Requires High Perf GPU" and the warning won't go away after the app stops using it (which presumably happens fractions of a second later). There's a race condition here, which I guess we're losing.

The first idea that comes to mind is for gfxCardStatus to grant a grace period after disconnecting power before posting the warning. My laptop doesn't have a discrete GPU so I can't test it out, but the original report is here: https://gitlab.com/gnachman/iterm2/issues/6541

**Comment by codykrieger** [comment]
Thanks for the report, @gnachman.

I think the issue here is that gfxCardStatus' detection of GPU changes is via the “display reconfiguration” callback, which is not necessarily guaranteed to fire with every GPU mux event. I'd like to find a better way of reliably detecting those events, but I'm not sure how best to do that at the moment.

It may be time to dive back into the disassembly of AppleGraphicsControl and friends to see if I can receive a callback from the driver itself when these events happen.

**Comment by codykrieger** [comment]
...granted, actual GPU mux events are also not exactly what we want in this case…we really want events to the effect of “new AppleGraphicsControl client connected that desires the discrete GPU” and the equivalent disconnect event, both of which may happen without a mux event occurring, but should cause us to invalidate our state re: which apps are asking for the discrete GPU.

**Comment by codykrieger** [comment]
Duping this forward to #312 which is tracking a bunch of these racy cases.
