### ISSUE TITLE
Screen pixelating when switching to Integrated

### ISSUE THREAD

**Issue by otbones** [codykrieger/gfxCardStatus#299]
I'm using a 2010 macbook pro and starting this morning, my screen has gone completely buggy when switching to integrated-only mode (I cant use dynamic switching because my computer has kernel panics and shuts down when using discrete). I downloaded the newest version of gfx which said to fix the issue, but the problem has persisted. Thanks in advance for your help!

**Comment by codykrieger** [comment]
Hey there @otbones—if you're using the latest version of gfxCardStatus, it's not causing your garbled screen. I think it's probably time for a machine replacement if your machine is behaving like that. Sorry!
