### ISSUE TITLE
Truncated notification

### ISSUE THREAD

**Issue by atdr** [codykrieger/gfxCardStatus#300]
I'm seeing the notification body text truncated when switching *back* to the integrated GPU—note that the notification for switching to the discrete GPU is **not** truncated.

![screen shot 2018-05-11 at 14 50 02](https://user-images.githubusercontent.com/10052770/39943427-b3b39e38-555a-11e8-8477-611a4728766e.png)
![screen shot 2018-05-11 at 14 48 33](https://user-images.githubusercontent.com/10052770/39943437-b71ed11e-555a-11e8-8e46-8e61540082c6.png)

Running macOS 10.13.4 on a MacBook Pro (15-inch, 2017).

**Comment by codykrieger** [comment]
@atdr Thanks for the report. Not sure what this could be off the top of my head, but I'll try digging into this at some point.
