### ISSUE TITLE
Will Not Stay on Integrated Only

### ISSUE THREAD

**Issue by Dave1112** [codykrieger/gfxCardStatus#301]
I have Early 2011 MBP with discrete GPU failing.  Running a mod to require integrated only, even at startup.  

Booted in single user -- 

------

nvram fa4ce28d-b62f-4c99-9cc3-6815686e30f9:gpu-power-prefs=%01%00%00%00

nvram boot-args="-v"

reboot

------

Been running this a few days.  Today, for some reason, machine switched to discrete card.  

Want to use gfx card status to easily switch back to integrated when needed.  Problem is, I cannot select integrated only, it keeps switching to discrete only when I select integrated only.  Activity monitor is showing integrated still.

**Comment by codykrieger** [comment]
This sounds like #103 and/or compatibility issues with Sierra/High Sierra (#240, #282).
