### ISSUE TITLE
MacOS 10.14 - Kernel Panic

### ISSUE THREAD

**Issue by austin-thesing** [codykrieger/gfxCardStatus#302]
I'm running the developer beta of MacOS 10.14 and something in the app is causing a Kernel Panic failure that forces my MacBook Pro 15" to shut down instantly upon the Kernel Panic and then restart.

Narrowed it down to this app by removing start up apps one by one.

**Comment by austin-thesing** [comment]
@codykrieger where would I find this?

**Comment by austin-thesing** [comment]
I can't find any panic files in the logs... Which is weird because when I read the errors when my computer restarted it mentioned kernel panics in them...

**Comment by DeputyDoug** [comment]
Here is my panic report. I have a similar issue:
Anonymous UUID:       4339FC1B-0210-092B-991D-DCA7CDAC2EBC

Wed Aug  8 22:15:22 2018

*** Panic Report ***
panic(cpu 1 caller 0xffffff7f8b9a09e9): "GPU Panic: mux-regs 5 3 7f 0 0 0 severity 3 WS-ready 1 switch-state 0 IG FBs 0 EG FBs 1:3 power-state 0 3D idle HDA idle : NVRM[0/1:0:0]: Read Error 0x00000100: CFG 0xffffffff 0xffffffff 0xffffffff, BAR0 0xd2000000 0xffffff91287ab000 0x0a5480a2, D0, P2/4\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGraphicsControl/AppleGraphicsControl-3.16.21/src/AppleMuxControl/kext/GPUPanic.cpp:162
Backtrace (CPU 1), Frame : Return Address
0xffffff8113d233f0 : 0xffffff800a6505f6 
0xffffff8113d23440 : 0xffffff800a77d604 
0xffffff8113d23480 : 0xffffff800a76f0f9 
0xffffff8113d23500 : 0xffffff800a602120 
0xffffff8113d23520 : 0xffffff800a65002c 
0xffffff8113d23650 : 0xffffff800a64fdac 
0xffffff8113d236b0 : 0xffffff7f8b9a09e9 
0xffffff8113d23710 : 0xffffff7f8c4d9441 
0xffffff8113d237d0 : 0xffffff7f8c5a51ca 
0xffffff8113d23810 : 0xffffff7f8c5a5235 
0xffffff8113d23890 : 0xffffff7f8d56b7f0 
0xffffff8113d239b0 : 0xffffff7f8c5c6d35 
0xffffff8113d239d0 : 0xffffff7f8c4e0048 
0xffffff8113d23a80 : 0xffffff7f8c4dda84 
0xffffff8113d23c70 : 0xffffff7f8c4dec41 
0xffffff8113d23d50 : 0xffffff7f8c48a61e 
0xffffff8113d23db0 : 0xffffff7f8d407839 
0xffffff8113d23e10 : 0xffffff7f8d407bb8 
0xffffff8113d23e30 : 0xffffff800ac9693c 
0xffffff8113d23ea0 : 0xffffff800ac96866 
0xffffff8113d23ed0 : 0xffffff800a689e74 
0xffffff8113d23f40 : 0xffffff800a689965 
0xffffff8113d23fa0 : 0xffffff800a6014f7 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleMuxControl(3.16.21)[B4DB1D7A-D4DE-3965-94DC-05CE8B9F2802]@0xffffff7f8b992000->0xffffff7f8b9a4fff
            dependency: com.apple.driver.AppleGraphicsControl(3.16.21)[2EB9A384-439B-3BDC-927C-34E390CB0E59]@0xffffff7f8b94c000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[8794C760-FDD9-3664-ADED-4A9BBEC6E517]@0xffffff7f8b3a3000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[C08F7FC1-78A4-3A1B-BFE2-C07080CF2048]@0xffffff7f8ae94000
            dependency: com.apple.iokit.IOGraphicsFamily(517.22)[2AEA02BF-2A38-3674-A187-E5F610FD65B7]@0xffffff7f8b635000
            dependency: com.apple.AppleGraphicsDeviceControl(3.16.21)[F8503E88-24EF-3DBA-A4D6-FA1CE4C47427]@0xffffff7f8b93a000
         com.apple.nvidia.classic.NVDAResmanTesla(10.0.4)[F8258F0F-61AD-30F4-BDD5-B18CCAAE535A]@0xffffff7f8c488000->0xffffff7f8c6f0fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[C08F7FC1-78A4-3A1B-BFE2-C07080CF2048]@0xffffff7f8ae94000
            dependency: com.apple.iokit.IONDRVSupport(517.22)[5672A7EF-44E8-3897-90DE-DAF4C1488143]@0xffffff7f8b968000
            dependency: com.apple.iokit.IOGraphicsFamily(517.22)[2AEA02BF-2A38-3674-A187-E5F610FD65B7]@0xffffff7f8b635000
         com.apple.nvidia.classic.NVDANV50HalTesla(10.0.4)[5DCF031B-F81F-32A3-ADCD-18E16EAC7CF0]@0xffffff7f8d447000->0xffffff7f8d6effff
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.4)[F8258F0F-61AD-30F4-BDD5-B18CCAAE535A]@0xffffff7f8c488000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[C08F7FC1-78A4-3A1B-BFE2-C07080CF2048]@0xffffff7f8ae94000
         com.apple.driver.AGPM(110.23.24)[F00AE848-ADD1-378F-8576-2D312C49D458]@0xffffff7f8d404000->0xffffff7f8d41bfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[C08F7FC1-78A4-3A1B-BFE2-C07080CF2048]@0xffffff7f8ae94000
            dependency: com.apple.driver.IOPlatformPluginFamily(6.0.0d8)[122FC50D-8A9C-37D8-9528-A38F45906EA9]@0xffffff7f8cf9f000
            dependency: com.apple.iokit.IONDRVSupport(517.22)[5672A7EF-44E8-3897-90DE-DAF4C1488143]@0xffffff7f8b968000
            dependency: com.apple.iokit.IOGraphicsFamily(517.22)[2AEA02BF-2A38-3674-A187-E5F610FD65B7]@0xffffff7f8b635000
            dependency: com.apple.AppleGraphicsDeviceControl(3.16.21)[F8503E88-24EF-3DBA-A4D6-FA1CE4C47427]@0xffffff7f8b93a000

BSD process name corresponding to current thread: kernel_task

Mac OS version:
17C88

Kernel version:
Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
Kernel UUID: 87641697-A3DD-30C4-B010-E65ECE57550B
Kernel slide:     0x000000000a200000
Kernel text base: 0xffffff800a400000
__HIB  text base: 0xffffff800a300000
System model name: MacBookPro6,2 (Mac-F22586C8)

System uptime in nanoseconds: 39227271416216
last loaded kext at 11198040127811: com.apple.driver.AppleXsanScheme	3 (addr 0xffffff7f8dd45000, size 32768)
last unloaded kext at 7700906265650: com.apple.driver.AppleXsanScheme	3 (addr 0xffffff7f8dd45000, size 32768)
loaded kexts:
com.mackeeper.kext.Firewall	2.15
com.rim.driver.BlackBerryUSBDriverInt	0.0.68
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.driver.AGPM	110.23.24
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleMikeyHIDDriver	131
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleHDA	280.12
com.apple.AGDCPluginDisplayMetrics	3.16.2
com.apple.driver.AppleMikeyDriver	280.12
com.apple.driver.AGDCBacklightControl	3.16.2
com.apple.driver.AppleHV	1
com.apple.GeForceTesla	10.0.4
com.apple.driver.AppleIntelHDGraphics	10.0.4
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleIntelHDGraphicsFB	10.0.4
com.apple.driver.eficheck	1
com.apple.driver.AppleMuxControl	3.16.21
com.apple.driver.AppleSMCLMU	211
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleMCCSControl	1.5.3
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleOSXWatchdog	1
com.apple.iokit.IOBluetoothSerialManager	6.0.2f2
com.apple.driver.pmtelemetry	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleUSBTCButtons	254
com.apple.driver.AppleUSBTCKeyboard	254
com.apple.driver.AppleIRController	352
com.apple.filesystems.apfs	748.31.8
com.apple.filesystems.hfs.kext	407.30.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.iokit.SCSITaskUserClient	404.30.2
com.apple.driver.AirPort.Brcm4331	800.21.30
com.apple.driver.AppleFWOHCI	5.5.8
com.apple.iokit.AppleBCM5701Ethernet	10.3.1
com.apple.driver.AppleAHCIPort	329
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	220.0.0
com.apple.nke.applicationfirewall	183
com.apple.security.TMSafetyNet	8
com.apple.security.quarantine	3
com.apple.IOBufferCopyEngineTest	1
com.apple.driver.AppleIntelCPUPowerManagement	220.0.0
com.apple.driver.AppleXsanScheme	3
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	280.12
com.apple.kext.OSvKernDSPLib	526
com.apple.nvidia.classic.NVDANV50HalTesla	10.0.4
com.apple.nvidia.classic.NVDAResmanTesla	10.0.4
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IOSurface	209.2.2
com.apple.driver.AppleGraphicsControl	3.16.21
com.apple.driver.AppleHDAController	280.12
com.apple.iokit.IOHDAFamily	280.12
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.iokit.IONDRVSupport	517.22
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.iokit.IOFireWireIP	2.2.8
com.apple.iokit.IOSerialFamily	11
com.apple.AppleGPUWrangler	3.16.2
com.apple.AppleGraphicsDeviceControl	3.16.21
com.apple.iokit.IOGraphicsFamily	517.22
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.usb.cdc.ncm	5.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.2f2
com.apple.iokit.IOBluetoothFamily	6.0.2f2
com.apple.driver.AppleUSBMultitouch	261
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.iokit.IOSCSIMultimediaCommandsDevice	404.30.2
com.apple.iokit.IOBDStorageFamily	1.8
com.apple.iokit.IODVDStorageFamily	1.8
com.apple.iokit.IOCDStorageFamily	1.8
com.apple.iokit.IOAHCISerialATAPI	267
com.apple.iokit.IOAHCIBlockStorage	301.20.1
com.apple.iokit.IOFireWireFamily	4.6.8
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBEHCIPCI	1.2
com.apple.driver.usb.AppleUSBEHCI	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOBufferCopyEngineFamily	1
com.apple.driver.DiskImages	480.30.2
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.30.4
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140.30.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOUSBMassStorageClass	4.0.4
com.apple.driver.AppleUSBComposite	900.4.1
com.apple.iokit.IOSCSIBlockCommandsDevice	404.30.2
com.apple.iokit.IOSCSIArchitectureModelFamily	404.30.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.iokit.IOReportFamily	31
com.apple.iokit.IOTimeSyncFamily	650.5
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMCRTC	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF
Model: MacBookPro6,2, BootROM MBP61.005A.B00, 2 processors, Intel Core i7, 2.66 GHz, 8 GB, SMC 1.58f16
Graphics: Intel HD Graphics, Intel HD Graphics, Built-In
Graphics: NVIDIA GeForce GT 330M, NVIDIA GeForce GT 330M, PCIe, 512 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353237334348302D4346382020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353237334348302D4346382020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.2f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: SanDisk Ultra II 960GB, 960.2 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: IR Receiver
USB Device: Built-in iSight
Thunderbolt Bus:

**Comment by austin-thesing** [comment]
@DeputyDoug I haven't seen any more Kernel panics on my install of late... Since the initial couple while running the beta of Mojave. Which version of MacOS are you running?

**Comment by DeputyDoug** [comment]
OS High Sierra 10.13.6
I had my consultant clean up the Mac. I also reduced the number of open
tabs on my browser. That seems to have done the trick. I'm still running
close to my RAM limit. There might be a solution by eliminating some of the
Google Chrome Helper pieces I find in Activity Monitor. But, generally,
things are better.

**Comment by codykrieger** [comment]
Tracking in #310; closing.

**Comment by macjeff** [comment]
I have the same issue on multiple macs.  Started with 10.14.4 beta 2 and continues through beta 4.  I have tried to contact BlueStacks from email multiple times but no response.  I have checked as of today and on latest version of BlueStacks.
