### ISSUE TITLE
Menu selection not working or reporting incorrectly

### ISSUE THREAD

**Issue by joewbrown** [codykrieger/gfxCardStatus#304]
Regularly when trying to choose a display mode, the option selected doesn't work and I can't get the machine to stay in Integrated Only mode. See video: https://drive.google.com/open?id=1rDbpS2XgRWp-wt7Rb_XY5j7FdzsK0b5B

Macbook Pro 15" Late 2015, MacOS 10.13.5

**Comment by codykrieger** [comment]
This is #242 / #103.
