### ISSUE TITLE
'Integrated only' option doesn't switch back when possible

### ISSUE THREAD

**Issue by mrjohnc** [codykrieger/gfxCardStatus#306]
Sorry for the poor title, I'm struggling to know how to explain the issue. 

I want my MacBook to only use the integrated graphics, its one of the old ones with the kernel panic issues. 

When chose 'Integrated only' from the option it often switches to 'Discrete Only' when browsing (I know there are some processes which require this). However it does not switch back to the integrated graphics when I stop using something that requires the discrete graphics card and I have to manually press the 'Integrated only' button. Once it switches into 'Discrete only' it never switches back to using the integrated card automatically.

**Comment by codykrieger** [comment]
This is #107.
