### ISSUE TITLE
Status of MBP 2010 Graphics Problem on High Sierra

### ISSUE THREAD

**Issue by wagle** [codykrieger/gfxCardStatus#307]
This is a question, not a problem report.  I didn't see the usual way of marking that distinction here.

Two years ago, my MBP 2010 started crashing if I didn't have my external monitor plugged in.

A year ago, it started crashing all the time, and soon it would take a dozen tries to boot.  For a week or two, I tried all sorts of graphics card magic (this app mostly, plus something that had me boot archlinux to rejigger some low-level graphics setting.  Finally, it just would not boot at all, and decided to permanently "swallow" a dvd.

I declared it dead just over a year ago, removed its SSD, and stuck it on a shelf since then.  Three days ago, the topic of old hardware came up, some local people on slack insisted that you still could get apple to replace the motherboard if you asked the right person.

What the heck?  The original spinner disk was now a archive disk, so I plugged it in to see what happened.  Well, it was running Yosemite, and worked just fine for a day, modulo a dead battery and a reset prom or three ("it's 4pm December 31, 2000, really!") .  So to see if it was worth re-modernizing with a new SSD, new battery, and High Sierra (would be worth a year or two?), I went to two apple hard support places.  They went "meh", and like that.

**So the question is**, how do I tell if the graphics problem has gone away by some means in High Sierra?  It ran fine for 12 hours, doing not much of anything.  Do I cancel my orders for a new ssd and battery, or hope for best?  I'm hoping to find someone with a better chance of _guessing_ right than me.  8)

**Comment by codykrieger** [comment]
It seems pretty unlikely to me that any of the issues you're experiencing would go away with High Sierra. The vast majority of the issues people tend to experience with dual-GPU MacBook Pros are hardware problems. ¯\\\_(ツ)\_/¯

**Comment by wagle** [comment]
I figured High Sierra might finally have a software workaround for the hardware problem (eg, the Linux Kernel source has a whole gamut of hardware workarounds.

But, if I have the timeline right, my problems started with the upgrade from Yosemite to El Capitan, then got worse when I upgraded from there to Sierra.  Well, I'll find out soon if High Sierra works for it.
