### ISSUE TITLE
Mojave 10.14

### ISSUE THREAD

**Issue by simonwaw** [codykrieger/gfxCardStatus#309]
Since upgrading to Mojave I'm unable to select 'Integrated Only'. 

The top menu bar still shows the 'i' icon however clicking on the menu - the selection shows as - 'Discrete Only'.  GPU still changes between the Intel HD Graphics 4000 / Nvidia Geforce GT 650 based on app usage.

**Comment by codykrieger** [comment]
Tracking in #310; closing.
