### ISSUE TITLE
Unable to switch to integrated

### ISSUE THREAD

**Issue by saqibhasan** [codykrieger/gfxCardStatus#313]
For some reason, I cannot select just the integrated chip - it keeps switching to discrete but literally nothing else is running concurrently.

Issue is on 10.13.6 on a MBP 2011 (the AMD Radeon HD 6750M had crapped out so can't run anything intense on this at the moment or it goes haywire).

Any help please?

**Comment by codykrieger** [comment]
Closing in favor of #310 and related issues.
