### ISSUE TITLE
Integrated GPU does not work

### ISSUE THREAD

**Issue by Buhtje** [codykrieger/gfxCardStatus#315]
I have been using this app for the MacBook Pro 2018 I7 8550, 6-core. It has an Intel UHD 630 and an AMD Radeon Pro 560X. 

Using the app to force using the integrated graphics, forces it into the dedicated AMD card. Clicking on only dedicated graphics also forces it into the dedicated AMD card. So, dynamic switching and dedicated options are working as expected, but not for the integrated only graphics. 

Are there any known problems of this? Maybe the use of Apple T2 chip? 
If so, do you think this can be fixed? I hope so. Processing.org application eats my battery.

**Comment by codykrieger** [comment]
Duping to #310.
