### ISSUE TITLE
Gfx Card 2.3 doesn't allow to switch graphic card (one card faulty) Macbook pro 2009 (Sierra)

### ISSUE THREAD

**Issue by gluon1976** [codykrieger/gfxCardStatus#322]
Hi to all,

I'm really sorry if that issue may have been discussed already a long time ago. I'm brand new here.
I friend of mine gave me a faulty macbook pro 17" 2009. The main screen stays black but I can plug an external monitor. I understand it's the famous problem with faulty video card.
I freshly installed a patched 10.12  that works very well.
There is a Nvidia 9400M and a 9600GT in the mac. I don't know which one is faulty.
I downloaded Gfx Card 2.3 but I can't switch to the other card so I force the main monitor to get back to like.
Any idea?
Thank you so much!

**Comment by codykrieger** [comment]
Hi @gluon1976—with the 2008-2009 MacBook Pros, you don't need gfxCardStatus at all to switch GPUs. Just quit gfxCardStatus, go to System Preferences > Energy Saver, and select “Higher Performance” for the 9600GT or “Better Battery Life” for the 9400M. Hopefully that helps you determine which GPU is faulty.
