### ISSUE TITLE
Forcing Integrated GPU is not working on Macbook Pro 2019 i9 8cores Vega 20

### ISSUE THREAD

**Issue by jlingo527** [codykrieger/gfxCardStatus#323]
I just received my new macbook pro 2019 and it wouldn't let me force to Integrated CPU.
I can only either click on Discrete or Dynamic switching.
Thank you,

**Comment by codykrieger** [comment]
Perhaps you're running into one of the issues described in #321 / #310?

**Comment by jlingo527** [comment]
Hi There,

My problem is when it didn’t let me tick on “Integrated Only” at all. Everytime, I ticked on “Integrated Only” the one got ticked “Discrete Only”.

Thank you in advance,

Best Regards,

Jeffri

**Comment by codykrieger** [comment]
Yeah, then this is #321 / #310.

**Comment by jlingo527** [comment]
Hi Yes,

The patch on #310 worked.
Thank you,

👍🏻
