### ISSUE TITLE
seeking workaround to install and activate GFXcardstatus on 2011 MbPro using TDm from other MacBook pro... 

### ISSUE THREAD

**Issue by GearheadInLA** [codykrieger/gfxCardStatus#324]
Is there a way to do this?  It seems GFXcardstatus app can be copied to the app folder of the TDM (f'd up) MacBook. of course the preference files can be moved across. But it doesn't see the cards on the TDM mac, it goes to the host mac that is just fine.  It would be good if this could be installed and run "remotely" as it would be the easiest fix to get the 2011 to ignore the dead AMD card 100% of the time and just use the integrated card as if it was the only one there.   @codykrieger your thoughts? thanks.

**Comment by GearheadInLA** [comment]
@codykrieger   your thoughts?  thanks.

**Comment by codykrieger** [comment]
@GearheadInLA That's not how Target Disk Mode works, unfortunately.

When you've got a Mac in that mode, macOS is not really running at all—only some low-level code that knows how to export the internal disk as a Thunderbolt peripheral.

**Comment by GearheadInLA** [comment]
Thanks.  I was hoping there was a workaround to initiate/set/trigger/control your software "remotely" so the f'd up 2011 could be restarted on integrated GFXCard only and forever?  Or I can still start the 2011 in safe mode --  it's REALLY hard to read the screen since it's green-white/weirdly interlaced, but still possible --  and (perhaps) manually enter via terminal what you've made the GUI do for the user when GFXcardstatus is run normally?

**Comment by codykrieger** [comment]
@GearheadInLA Nope, sorry, there's no command equivalent for what gfxCardStatus does.
