### ISSUE TITLE
Blackscreen on session exit

### ISSUE THREAD

**Issue by Donothir** [codykrieger/gfxCardStatus#325]
When I'm on "Integrated Only" mode and I exit my session, I always get a black screen. The computer shut off the monitor, but the computer is still responsive. I can log on in a session, restart the computer and so on using the keyboard.

If I am in a black screen state and start again my session and log off immediately using the keyboard, the screen comes back to life. If I'm taking a long time in the session and log off, the screen doesn't come back to life. So it look like the way the exit is handled by the application, maybe the automatic mode should be toggled on exit to ensure the computer behaves by default.

Computer: MacBook Pro (17-inch, Early 2011) - MC725LL/A

**Comment by codykrieger** [comment]
@Donothir That's actually exactly what gfxCardStatus does today—on exit, it turns on automatic graphics switching. But perhaps gfxCardStatus is not terminated gracefully when you log off?
