### ISSUE TITLE
MBP 2010 15'' GPU Problem

### ISSUE THREAD

**Issue by brunoaraujo07** [codykrieger/gfxCardStatus#327]
Hello,
First I would like to congratulate you on gfxCardStatus, it is helping me a lot with my 2010 MBP with NVIDIA GeForce GT 330M GPU problem. Every time my MBP uses NVIDIA it reboots and displays an error screen, but when I use 'Only Integrated' everything happens normally. Is there any way to leave MBP all the time using just integrated?

If there is how, help me, please.

**Comment by codykrieger** [comment]
@brunoaraujo07 Unfortunately there's no way to do that. Sorry :/
