### ISSUE TITLE
Does not let me change to Integrated Only

### ISSUE THREAD

**Issue by m-damgaard** [codykrieger/gfxCardStatus#328]
Whenever I am on Dynamic Switching setting, my macbook pro is on its integrated GPU: Intel UHD Graphics 630, but whenever I switch the setting to Integrated Only, it changes to my graphics card Radeon Pro 555x.

My macbook pro is from 2018 15 inch with touch bar. I am running MacOS Catalina 10.15.1 
Please help... this issue is pissing me off, that I cannot only use my integrated setting...

**Comment by codykrieger** [comment]
This is #321 / #312 / #310.
