### ISSUE TITLE
using DuetDisplay and iPad as external monitor

### ISSUE THREAD

**Issue by misbell** [codykrieger/gfxCardStatus#329]
FIrst, thanks for the great work. I just got a refurb 2015 MacBook Pro 15" and the screen flashing convinced me my computer was toast, until your software flitted across my radar. Now the device is stable as a rock.

Here's the issue. When I choose Integrated, then attach the iPad "monitor", the checked off item on the gfx menu becomes "Discrete", while the letter on the menu bar remains an "i". 

Here's a movie demoing.

[IMG_2322.MOV.zip](https://github.com/codykrieger/gfxCardStatus/files/4024638/IMG_2322.MOV.zip)

**Comment by codykrieger** [comment]
Sorry for the super long delay in getting back to you on this @misbell. This sounds like some combination of #312 and the issues noted in #310. I'll track this stuff there.
