### ISSUE TITLE
Color profile issues

### ISSUE THREAD

**Issue by gaioum** [codykrieger/gfxCardStatus#330]
Getting some color profile changes upon dynamic switching, using macOS 10.15.2 (19C57) on a MacBookPro16,1
Have to revert manually the color profile, or put the computer to sleep and wake up.
Quitting the app solves the pb.

**Comment by codykrieger** [comment]
@gaioum gfxCardStatus itself doesn't touch anything related to color profiles, so it's not gfxCardStatus causing the color profile switch per se—it's more likely related to the graphics switching subsystem itself.

Others that have seen issues like this have seen the situation improve/disappear by resetting their PRAM and/or NVRAM: https://support.apple.com/en-us/HT204063

**Comment by gaioum** [comment]
thanks!




Guillaume Raffi - Creative Producer

*+1 323 420 8770 - gaioum@gmail.com <gaioum@gmail.com>*
