### ISSUE TITLE
app no longer works. catalina 10.15.3, MacBook pro 2015, 15"

### ISSUE THREAD

**Issue by misbell** [codykrieger/gfxCardStatus#333]
![2020-02-13 at 9 53 PM](https://user-images.githubusercontent.com/356572/74497289-460f3f80-4eab-11ea-9bd2-44668a577481.png)

https://www.dropbox.com/s/g3zezwdsnmcg18s/IMG_2574.mov?dl=0

yes, I've turned off automatic switching in system preferences.

result of its no longer working is constant hangs and flashes. switches to GPU no matter what I do.

also, sometimes "integrated only" check is on, but GPU is clearly indicated.

![2020-02-13 at 9 59 PM](https://user-images.githubusercontent.com/356572/74497598-24fb1e80-4eac-11ea-922d-2207deb79fae.png)

**Comment by codykrieger** [comment]
Two things:

- When you're using gfxCardStatus, you don't need to fiddle with the `Automatic graphics switching` setting in System Preferences > Energy Saver; gfxCardStatus manages that setting for you. When you disable that setting yourself, you're turning on the discrete GPU and preventing the integrated GPU from being used.
- A broad range of compatibility issues are being tracked in #310, and it sounds like you're running into some of those things, so I'll close this ticket in favor of that one.

**Comment by misbell** [comment]
1. wow, good to know. thank you.
2. sounds good. 

Thanks for the quick response.
