### ISSUE TITLE
Menu Bar Icon Offset

### ISSUE THREAD

**Issue by andre4ik3** [codykrieger/gfxCardStatus#336]
On the latest macOS (Big Sur, Developer Beta) the menu bar icon is offset
<img width="121" alt="Снимок экрана 2020-06-23 в 00 04 11" src="https://user-images.githubusercontent.com/62390580/85343562-128d9300-b4e5-11ea-8071-c981fd114cdc.png">

macOS Beta v11.0 (20A4299v)
gfxCardStatus v2.3 (2.3)

**Comment by codykrieger** [comment]
@andre4ik3 Thanks. I've had a couple reports of this via email as well.

**Comment by luke-strzelczyk** [comment]
Same here. MacOS Big Sur Beta 6. Are there any chances for a fix?

**Comment by joeldonaldson** [comment]
Also on a 3 monitor setup with dark mode, the menu bar icon doesn't show white.
![image](https://user-images.githubusercontent.com/62966950/93094888-17875c00-f668-11ea-8baf-109467806b76.png)

**Comment by marshalleq** [comment]
Offset for me too.

**Comment by hobbo91** [comment]
This is still happening with 20B5022a (Release Candidate) Big Sur - as cool as this app is, it's playing havoc with my OCD! Any chance of a fix for this issue? 

<img width="337" alt="Screenshot 2020-11-07 at 23 10 53" src="https://user-images.githubusercontent.com/74117282/98453212-a7202700-214e-11eb-8fea-f99b65d706c1.png">
<img width="331" alt="Screenshot 2020-11-07 at 23 11 45" src="https://user-images.githubusercontent.com/74117282/98453213-a7b8bd80-214e-11eb-929f-38a0b915d4db.png">

**Comment by codykrieger** [comment]
Pull Requests for this issue would be welcome. If someone sends one, I'll do my best to get an update  out.

**Comment by dylanbromby** [comment]
Another 👍 for adjusting the icon offset 😄 .

**Comment by hirobg** [comment]
<img width="128" alt="Screenshot 2020-11-13 at 10 15 52" src="https://user-images.githubusercontent.com/56501304/99044923-371fff80-2599-11eb-906d-a8750a3167f5.png">
Big Sur ofcialy released for public and yeah i also have problem with the icon :) Great program but this icon is anoying now :) please fix it. Thanks for your hard work.

**Comment by coverxit** [comment]
#344 My quick fix for Big Sur.

**Comment by codykrieger** [comment]
I've merged @coverxit's fix in #344 (thanks!), and I'll try my best to get out an official update (the first one in 8 years!) in the next couple of days here.

**Comment by codykrieger** [comment]
Thanks for bearing with me here folks—I'm taking this opportunity to do a lot of long-overdue cleanup and a couple small bug fixes:

```
362 files changed, 14007 insertions(+), 17614 deletions(-)
```

I'll have a beta release prepared soon for folks to try out.

**Comment by codykrieger** [comment]
For the record: notarization is the worst.

**_The worst._**

😐

**Comment by codykrieger** [comment]
v2.5b1 now available for those that would like to give it a shot! https://gfx.io/downloads/gfxCardStatus-2.5b1.zip

**Comment by joeldonaldson** [comment]
So far so good.  Minor thing, with the changes to the menu bar, can the icon stay the same color when clicked?

Joel

On Nov 20, 2020, at 10:57 AM, Cody Krieger <notifications@github.com> wrote:


v2.5b1 now available for those that would like to give it a shot! https://gfx.io/downloads/gfxCardStatus-2.5b1.zip <https://gfx.io/downloads/gfxCardStatus-2.5b1.zip>

**Comment by ruchern-chong** [comment]
v2.5b1 works fine for me. Thanks @codykrieger

**Comment by codykrieger** [comment]
The v2.5 beta seems to be working for people, so I'mma go ahead and close this ticket. Thanks to everyone that reported the issue and helped test the beta!

**Comment by ruchern-chong** [comment]
@codykrieger will there be a final release version for 2.5 rather than 2.5b4?

**Comment by codykrieger** [comment]
@ruchern-chong Yeah, within the next couple days probably. v2.3 and v2.5b4 users will see the update.
