### ISSUE TITLE
Why does "Dynamic switching" change by itself to "Discrete" and apparently slow the Macbook?

### ISSUE THREAD

**Issue by JoshuaFox** [codykrieger/gfxCardStatus#338]
([Related Stack Exchange question](https://apple.stackexchange.com/questions/396447/).)

I have two external monitors with my 2017 Macbook Pro v.10.15.6. Sometimes it slows -- the mouse lags badly. 

My goal is  better performance, even if it means more power consumption.

Sometimes I find that  the selection in gfxCardStatus  has changed from "Dynamic switching" to "Discrete only." It seems that the lagging starts just when that happens.

- Is it possible that "Discrete only" slows the computer?  Logically, Discrete is the fastest mode.
- Why does this selection switch automatically? 
- How can I force it to stay on "Dynamic switching"?  

(This relates to  [another question](https://apple.stackexchange.com/questions/394669/why-does-automatic-graphics-switching-keep-re-enabling-itself-without-my-involve), in which "Automatic graphics switching" under Energy saver was getting automatically enabled. I wrote a script to disable it on startup, but this setting too enables itself sometimes for no clear reason; apparently that is separate  from  "Dynamic switching" in gfxCard Status.)

**Comment by codykrieger** [comment]
If your goal is better performance regardless of power consumption, then the solution is really simple: quit gfxCardStatus, delete it, and disable automatic graphics switching in System Preferences > Energy Saver. That will cause the discrete GPU to be used all the time.

When gfxCardStatus is running, it manages the automatic graphics switching setting for you. Dynamic Switching is equivalent to having the automatic graphics switching checkbox checked.

**Comment by JoshuaFox** [comment]
@codykrieger  Thank you. That's helpful, and clarifies the relationship between gfXCardStatus and Energy saver.
