### ISSUE TITLE
not switching to iGPU

### ISSUE THREAD

**Issue by ilovefood2** [codykrieger/gfxCardStatus#339]
I have a macbookpro 16" on latest 10.15.6 and tried to use your program to set laptop use iGPU all the time. 
As I tested, under regular usage (no pro apps, just browsing and youtube), when set to dynamic, my laptop is using iGPU, however, when i choose "integrated only", immediately, it notifies my that i'm using discrete GPU ( i confirmed with what activity  monitor shows :High Perf.), no matter how many times I try, my laptop does not set to integrated GPU only. is this an known issue?

**Comment by ilovefood2** [comment]
![image](https://user-images.githubusercontent.com/4293869/90344233-c1ca8000-dfe5-11ea-8ede-230e7c4a33fe.png)

**Comment by codykrieger** [comment]
@ilovefood2: Thanks for the report. This is #331 / #310.
