### ISSUE TITLE
Unsupported machine

### ISSUE THREAD

**Issue by Duftbaum** [codykrieger/gfxCardStatus#340]
Hi everybody,

when I try to use gfxCardStatus the message "UnsupportedMachine" pops up.

**Machine Specs:**
MacBook Pro (13 Zoll, 2020, Four Thunderbolt 3 Connectors)
CPU: 2 GHz Quad-Core Intel Core i5
RAM: 16 GB 3733 MHz LPDDR4X
Graphic card: Intel Iris Plus Graphics 1536 MB
macOS: Catalina (10.15.6)

Is there any release planned or any workaround? 

Thanks in advance for your help :)

**Comment by codykrieger** [comment]
@Duftbaum: 13" MacBook Pros only have one GPU, so you have no need for gfxCardStatus.
