### ISSUE TITLE
Menu bar icon no longer shows properly on MacOS 10.14 Big Sur (Public Beta 8)

### ISSUE THREAD

**Issue by lestmak** [codykrieger/gfxCardStatus#342]
Spacing below the icon means that it is offset vertically relative to other menu bar icons.

<img width="87" alt="image" src="https://user-images.githubusercontent.com/72608237/95578613-11e52200-0a2c-11eb-8c0a-ab3e80b9f07e.png">

**Comment by lestmak** [comment]
Better image of problem: 

<img width="307" alt="image" src="https://user-images.githubusercontent.com/72608237/95578706-380ac200-0a2c-11eb-8731-bdc7bc398641.png">

**Comment by codykrieger** [comment]
This is #336.
