### ISSUE TITLE
No support for Macbook Pro with integrated GPU and eGPU 

### ISSUE THREAD

**Issue by marceliwac** [codykrieger/gfxCardStatus#347]
I am struggling to get this program to run with my Macbook Pro 13" Late 2019 which only has 1 (integrated) graphics card. I do have an eGPU _(enclosure is Razer Core X and GPU is AMD RX580)_. Does this app only support discrete (built-in) GPUs? 

I've tried both `v2.3` and `v2.5b4`.

**Comment by codykrieger** [comment]
gfxCardStatus is only designed to control the special GPU muxing hardware built into dual-GPU MacBook Pros. eGPUs are a whole different beast, and it's not especially clear what benefit gfxCardStatus could provide with eGPUs.
