### ISSUE TITLE
upgrade 2.4.4 to 2.5, Forced Integrated Modedoesn't work anymore

### ISSUE THREAD

**Issue by Exitneox** [codykrieger/gfxCardStatus#349]
MacBook Pro (15-inch, 2019), Radeon Pro 560X 4 GB

GFX 2.4.4i was working fine with Catalina, then came Big Sur, and still work fine (often in Discrete Mode)

Today it says 2.5 is out, went to 2.5 and now it doesn't work.
Event after cleaning and full/fresh install of gfx status

Automatic mode is fine, I got "I" or "d" icon upon application use and popup show which card is in use
Discrete Only, I got the "d" and the popup confirm I use the discrete one
Integrated only, show me the "d", confirmed by the "card in use being : radeon Pro, tick is on "Discrete Only"
a bit like the "integrated mode" acts as the Discrete mode.

Regards.

**Comment by Flydervish** [comment]
Similar issue. Using gfxcardstatus to force integrated mode due to faulty card. Macbook crashed after update to 2.5 due to dynamic switch. Reverting to older versions doesn't seem to work (macbook still crashing). Removed completely and reinstalled v2.3. Awaiting results.

**Comment by AgentMax81** [comment]
Same with MBP16" 2019. Force integrated GFX does not work.

**Comment by radamelo90** [comment]
Same error for MBP 15” mid 2010 High Sierra 10.13.6. Where can I get previous 2.5 version installer please. Thanks.

**Comment by kikiwora** [comment]
Same, MBP 16''

**Comment by AlpiJoe** [comment]
Unfortunately the same, with 2.5 the "Intergated Only" mode stopped working 😞. 

When I'm in "Dynamic Switching" and I click on the "Integrated Only" mode, then the app switches into "Discrete Only" mode (I don't even understand why). When I click on "Integrated Only" again, then the app switches into that mode, but the GPU remains the dedicated one 😞.

**Comment by jonhugo** [comment]
@Flydervish has the fix at least for now - MBP 16" i9 
Download the older version and integrated works, just delete 2.5 until he makes another update.
I downloaded 2.4.4i

**Comment by codykrieger** [comment]
“gfxCardStatus v2.4.4i” is an unsupported third-party fork that I have no control over, so if you choose to use that version, just be aware that I can't help you with any issues you may run into.

gfxCardStatus will gain fixes for some of the issues the v2.4.4i fork addresses (like #107) in a future update.
