### ISSUE TITLE
Update renders MacBook useless 

### ISSUE THREAD

**Issue by mickstatham** [codykrieger/gfxCardStatus#350]
Seconds after updating to the latest version today my 2013 MacBook Pro shut down and will no longer boot into OS. In fact, it doesn’t even get as far as the OS, it just gets to half way through the apple progression bar then shuts down. At one point it was stuck in a reboot cycle which took ages to stop. Coincidence?

**Comment by codykrieger** [comment]
@mickstatham Yikes, I'm sorry to hear that. It's extremely unlikely that gfxCardStatus itself caused this behavior—more likely you've got a hardware issue with your discrete GPU. Were you using gfxCardStatus to work around GPU switching-related crashes? Or just to save battery life / monitor power usage?

**Comment by mickstatham** [comment]
To be honest I’ve no clue. It’s been on the MacBook since I bought it and just ‘runs in the background’ doing its own thing. Got a message to update so I did. It was a long shot. Just thought I’d try. Can’t get into the damn thing at all. Can’t restore from time machine, cant wipe and reinstall, nada.

**Comment by codykrieger** [comment]
OK. If you've never really touched it, it should have just been in the default setting, which is to use macOS' built in automatic graphics switching feature.

Try resetting your SMC and PRAM: https://www.ifixit.com/Guide/How+to+reset+the+SMC+PRAM+and+NVRAM+on+a+Mac+Laptop/113252

**Comment by mickstatham** [comment]
Thanks Cody. I’ll give that a try. Wish me luck.

**Comment by codykrieger** [comment]
Good luck! 🙌 Let me know how you fare.

**Comment by mickstatham** [comment]
Hi Cody, latest update is that I’ve tried just about everything I can so I think it’s time to call it a day and invest in a new M1 model. Thanks for your help though, it’s greatly appreciated. Have a good one 🎄👍

**Comment by codykrieger** [comment]
I'm jealous! The M1 machines are really slick. I'm looking forward to upgrading once there are configurations available with 32GB+ of RAM. :)
