### ISSUE TITLE
GPU Notifications

### ISSUE THREAD

**Issue by MrMxDzn** [codykrieger/gfxCardStatus#351]
Hi,
I have the Problem, that the Notifications if the GPU changes are very short, so you can't read it or they aren't there

**Comment by codykrieger** [comment]
@MrMxDzn Can you please post a screenshot? I'm not sure exactly what you mean.

**Comment by MrMxDzn** [comment]
@codykrieger Sorry, that i haven't responded. I've attached a video to show you the problem.

https://user-images.githubusercontent.com/76188531/103311485-c59df280-4a1a-11eb-9846-a7884a8550e9.mov

**Comment by codykrieger** [comment]
For posterity: tracking in #358.
