### ISSUE TITLE
Forced integration in 2.5 switches back to discrete after a while

### ISSUE THREAD

**Issue by jimbojetlag** [codykrieger/gfxCardStatus#353]
Not sure if this is related to #349, but after the upgrade, forced integration jumps back to discrete **n** icon after a while.

**Comment by rowlandcarson** [comment]
I am having this problem too with v2.5.
MacBook Pro 15” mid-2010, Mac OS 10.13.6.
If I forget to keep an eye on it and switch it back to integrated, discrete will soon cause a system crash - as it did way back before I discovered gfxCardStatus.
Any fixes found yet?
in friendship 
Rowland

**Comment by codykrieger** [comment]
This isn't new to v2.5—this is a long-standing bug introduced by changes in macOS as far back as 10.9. If you're on Integrated Only, and you quit all of the apps that would have otherwise used the discrete GPU, the discrete GPU will turn on. Tracking a bunch of related cases in #310.
