### ISSUE TITLE
Recent update disabled gfx macbook fix 

### ISSUE THREAD

**Issue by GalacticOverlord** [codykrieger/gfxCardStatus#355]
Hello, like so many others I use the gfx card status app to fix the graphics card motherboard issue on 2010 Macbook Pros, and unfortunately the recent update has made it no longer functional.

Specifically, I'm getting the error message that you can't use integrated only while x, y, and z apps are running. Of course, before the update I never got this error message. This is terrible because it essentially makes my laptop unusable. I'm really hoping for a fix or workaround, since I work from my laptop, so this is fairly serious for me. Thank you.

**Comment by izoratti** [comment]
Trying to troubleshoot the problem, I experience something similar.
Unlike @GalacticOverlord, I sometimes had the issue of switching to Dynamic with the previous version, but that was easy to recognise (video hanging for a second or so), so I could close the app and revert to the Integrated mode. Now I do not see this happening, I sometimes check the menubar and I find the GPU is in Dynamic or Discrete mode, but the icon is still "i". 
Another issue (which I should report separately), is that it looks like it does not keep the last setting at restart.

**Comment by codykrieger** [comment]
@GalacticOverlord and @izoratti, what version were you using previously?

**Comment by GalacticOverlord** [comment]
I'm not 100% but pretty sure it was 2.4, and when I reverted back to 2.4, I
no longer have the problem (well it occasionally crashes, but I'm not sure
if that is due to GFX card status switching to discrete, or not).

**Comment by GalacticOverlord** [comment]
In 2.5, when I tried to switch to integrated, it gave me the error message
saying it couldn't do so when various apps are running, and they were all
standard apps I typically run, like Chrome or Evernote, etc.

**Comment by codykrieger** [comment]
@GalacticOverlord OK. That being the case, I'm duping this to #349. v2.4/2.4.4i/etc. are from an unsupported third-party fork that I have no control over.

Future (official) gfxCardStatus updates will incorporate some of the fixes included in the v2.4.x fork.

**Comment by GalacticOverlord** [comment]
Okay, thanks Cody.
