### ISSUE TITLE
Letter N for dedicated? Switching not working?

### ISSUE THREAD

**Issue by frostiex** [codykrieger/gfxCardStatus#356]
I have a late 2013 mbp 15"
It appears I have not noticed the gfx to ever switch if I leave it on Dynamics. Even if I hear the FAN blowing like crazy while gaming. The notification is alway  "i"
If I change it to Discreet ONLY...the letter is not D, but N

Posted screenshot [https://ibb.co/v4cQNns](url)

**Comment by coverxit** [comment]
Not sure what caused your fan issue. But for the N letter, I believe it stands for "NVIDIA".

**Comment by codykrieger** [comment]
This is probably #312. If you're on Dynamic Switching, macOS controls the GPU switching, not gfxCardStatus.

Also, yes, as @coverxit said, “n” is for NVIDIA and “i” is for Intel when you have the “use smart menu bar icons” preference enabled.
