### ISSUE TITLE
Cannot select different automatic switching modes after uninstall.

### ISSUE THREAD

**Issue by alexanderbath** [codykrieger/gfxCardStatus#359]
After uninstalling gfxCardStatus I now cannot choose to have automatic graphic switching enabled on battery but not on AC power in the default battery preferences panel. When I enable it on one, it automatically enables it on the other and vice versa.

**Comment by stanislav741** [comment]
Are you sure it was working different way before gfxCardStatus app?
As far as I know, "Automatic graphics switching" can be applied only regardless of Battery/Power Adapter tab.
On Big Sur the UI for that settings screen was changed so it might look less obvious there.

Here's how it used to look on Catalina:
https://support.apple.com/en-us/HT202043

**Comment by codykrieger** [comment]
The UI you see in System Preferences > Energy Saver is a function of your MacBook Pro model and the version of macOS you have. Uninstalling gfxCardStatus doesn't change anything about how that works.
