### ISSUE TITLE
Dedicated Graphics card not being used

### ISSUE THREAD

**Issue by theHazzard** [codykrieger/gfxCardStatus#363]
Is there a way to force a process to use the dedicated card? I have a AMD card that is not being used on games like Rust, or even on steam, when I switch the card to discrete only it does nothing :(

**Comment by codykrieger** [comment]
I'd suggest quitting gfxCardStatus and disabling automatic graphics switching in System Preferences > Energy Saver to see if that helps. If not, then it seems like a bug with the games.

**Comment by theHazzard** [comment]
thanks! I was unable to make it switch to the discrete graphics, I ended up using bootcamp with windows
