### ISSUE TITLE
Notifications disappear instantly

### ISSUE THREAD

**Issue by submarines-and** [codykrieger/gfxCardStatus#364]
Love the app, one issue however: The notifications that appear when graphics card are switched are disappearing instantly for me. I see them for maybe half a second (until they have fully appeared on the screen), then the banner goes away.

Tested with both alerts+banners.

My current config:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/3114694/111906555-50f2b700-8a51-11eb-85bc-77d0570003a5.png">

If I trace logs, I get nothing that looks suspicious (logs from switching back and forth)

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/3114694/111907221-a8465680-8a54-11eb-8ed7-1cd707bde55e.png">

**Comment by codykrieger** [comment]
Thanks @submarines-and. I saw this a bit on and off while developing the v2.5 update, but I thought I'd fixed it. Apparently not!

Tracking in #358.

**Comment by seralouk** [comment]
Hi I have a MacBook Pro with these specs:

<img width="275" alt="Screenshot 2022-02-11 at 15 18 24" src="https://user-images.githubusercontent.com/25902670/153607797-742915bc-382c-4567-80e8-97506fa5905c.png">


When I choose "Dynamic" or "Discrete" I get a notification that only appears for some milliseconds. I cannot read it as it disappears instantly. 
Moreover, when I click on "Integrated" a) nothing changes (weird) and b) no notification at all!

Any fix?
