### ISSUE TITLE
5600M not switchable

### ISSUE THREAD

**Issue by ltwin8** [codykrieger/gfxCardStatus#367]
Installed v2.5 on MacBook Pro 16", GPU: 5600M.

Problem:
select integrated graphic: it switches to dedicated and displays "d" 
select dedicated graphic: it switches to dedicated and displays "d" 
select automatic graphic: it switches to integrated and displays "i" until macOS "itself" required dedicated

**Comment by cibimo** [comment]
same problem

**Comment by RoadToDream** [comment]
@cibimo @david1asher @ltwin8 please consider this build
[gfxCardStatus.zip](https://github.com/codykrieger/gfxCardStatus/files/6794009/gfxCardStatus.zip)

**Comment by codykrieger** [comment]
This is likely a duplicate of #331, so we'll track this there.

**Comment by IslandOwnerHuang** [comment]
Same here
