### ISSUE TITLE
Network volume access?

### ISSUE THREAD

**Issue by Soneji** [codykrieger/gfxCardStatus#371]
Hi

I have been using your app for a long time but recently I got this message, I was wondering if you knew why this could be. 

![image](https://user-images.githubusercontent.com/12625848/127705333-20181a0e-77a8-464b-9aca-3a1cb9493e4c.png)

Thanks

**Comment by codykrieger** [comment]
Hi @Soneji—sorry for the delayed response on this. I've never seen that before. Where did you download gfxCardStatus from? Are any of the files in your home directory located on a network drive?

I believe that the only file gfxCardStatus accesses directly is `~/Library/Preferences/com.codykrieger.gfxCardStatus-Preferences.plist`.

**Comment by Soneji** [comment]
Hi
Turns out a bunch of apps I had installed started doing this after I mounted a network volume. I reckon it's some sort of lower level macOS thing
Thanks for the great app!
