### ISSUE TITLE
iMac Pro with two GPUs

### ISSUE THREAD

**Issue by meaganmargaret** [codykrieger/gfxCardStatus#373]
Looks like your software doesn't support my situation.  I have an iMac Pro, with it's internal GPU (a Vega 64X) and an external Thunderbolt attached eGPU with a AMD 6800XT.  

My systems shows the external GPU and I can switch to it in some software (Davinci Resolve, for instance), but again need a bit more control for other software programs.  That's why I hoped your software might work for me.

But, it won't load.  Any possibility you might want to support situations like mine in the future?

**Comment by codykrieger** [comment]
@meaganmargaret Sorry, gfxCardStatus is specifically designed to control the GPU muxing hardware on dual-GPU MacBook Pros. eGPU support isn't something that I have on the roadmap.

**Comment by meaganmargaret** [comment]
ok, thanks

Cody Krieger wrote on 10/26/21 3:48 AM:
