### ISSUE TITLE
Application doesn't run on M1 Max Macbook Pro with 24 GPU Cores

### ISSUE THREAD

**Issue by llebron** [codykrieger/gfxCardStatus#374]
Behavior: On launch, app displays this window:
![image](https://user-images.githubusercontent.com/3743450/148322494-fd93b8aa-899f-4e56-a42a-7a834803ba62.png)

Expected Behavior: App launches and works properly

Device Model: MacBook Pro (16-inch, 2021)
Chip: Apple M1 Max
GPU Cores: 24

**Comment by codykrieger** [comment]
Yes, this is expected. M1 machines only have a single GPU, so gfxCardStatus is useless to you.

**Comment by llebron** [comment]
Good point! :)
