### ISSUE TITLE
Mid-2010 Macbook Pro - Blue colour tint on nVidia GPU with gfxCardStatus

### ISSUE THREAD

**Issue by markc1984** [codykrieger/gfxCardStatus#88]
Hello,
I installed Mountain Lion on my Macbook Pro this afternoon and have discovered an issue with gfxCardStatus.

Basically while the gfxCardStatus is running and the nVidia GPU activates through any program that requests it, the whole screen changes to an odd blue colour cast, the only way to describe it is like as if a wrong colour profile has been installed. If I manually switch back to the Intel GPU or allow it to switch back by itself by closing all apps, the blue tint disappears. If I close gfxCardStatus without rebooting the computer the problem can be reproduced each and every time.

If I uninstall the program or prevent it from booting at startup and then repeat the above process the blue screen tint problem disappears, I've up to now been unable to reproduce this issue unless this program is running. 

Sorry if I haven't explained things very well, I hope it makes sense.

Could this be a specific issue with this particular model of MPB, this program and Mountain Lion?

Just FYI, I never had any of these issues with Lion.

**Comment by a-aladawy** [comment]
@umputun, Thanks for that workaround! works perfectly.

**Comment by jonathanpereira** [comment]
@umputun, Thanks a lot! You saved my life!
